### ISSUE TITLE
rsbuddy.com/raids is down

### ISSUE THREAD

**Issue by rsbfox** [rsbmatt/OSBuddy#101]

**Comment by UhWatchMe** [comment]
Exchange History also appears to be down. < Nevermind that, just took a long time to load.

**Comment by ThanksRSB** [comment]
Hiscores also seems to use old RSNs rather than the current/new ones/the ones that were chosen when they got the record(s).

**Comment by rsbfox** [comment]
@ThanksRSB  See #81

**Comment by rsbfox** [comment]
Working again.

**Comment by ThanksRSB** [comment]
http://i.imgur.com/Ifc2x2l.png
Nope
