### ISSUE TITLE
Jewelry: Option reorder teleport options on jewelry

### ISSUE THREAD

**Issue by jannicklorenzen** [rsbmatt/OSBuddy#103]
Making teleportation jewelry left-clickable for teleportation would be a great QoL update.
Adding it through the Runecrafting plugin would be optimal.

**Comment by rsbfox** [comment]
This fails the would 2007scape riot test. Although a lot of osbuddy updates do.
There were complaints about shift click option letting people 1 click tele with jewelry in inventory.

Runecrafters always wear the teleports. OSBuddy has never changed options on equipment. Could upset pkers and you get people teleporting by mistake when they go to take jewelry off.

Also this is just something if I think was polled by Jagex would never pass. Wait for osbuddy reply though. I am just giving devils argument on this one. I think all ideas should be suggested and considered.

Also uh the jewelry plugin would be the optimal one. Considering it already is checking most teleports anyway and someone left clicking to tele will need to need number of teles left in stack size.

**Comment by rsbfox** [comment]
If it was jewelry plugin option just to make all left click teleport in inventory I'd support. Cause you can already do it with shift reorder. Adding to jewelry plugin instead would just save people effort of setting that up and holding shift key. If they want to do this I will add which option is teleport to everything on. #76

**Comment by NoEffex** [comment]
The current plan is to support changing it in the inventory via the option reorder plugin.

**Comment by rsbfox** [comment]
https://rsbuddy.com/osbuddy/patch_notes/3.0.17
