### ISSUE TITLE
Slayer: Wilderness tasks doesn't fit in textbox

### ISSUE THREAD

**Issue by jannicklorenzen** [rsbmatt/OSBuddy#104]
Any task you get from Krystilia will have "in the wilderness" affixed to the task name. 
I suggest adding a skull icon somewhere in the overlay to indicate that it's in the wilderness.

![image](https://user-images.githubusercontent.com/30437792/28819097-5e317f02-76ad-11e7-848e-99dd776882a5.png)

OSBuddy v3.0.13

**Comment by pacmanfox** [comment]
![image](https://user-images.githubusercontent.com/30416150/29740603-2de5cb4e-8a28-11e7-9c28-8a61dafac803.png)

Still in v3.0.20

**Comment by rsbfox** [comment]
OSB-84
