### ISSUE TITLE
Woodcutting: OpenGL overlay issues

### ISSUE THREAD

**Issue by softwarez** [rsbmatt/OSBuddy#11]
- [x] overlay transparency not correct in OpenGL mode

Probably due to the rendering technique of this plugin.

Image for reference:
![overlay](http://i.imgur.com/Fw15h5e.png)

- [x] Z-index of the axe overlay is wrong in OpenGL mode (probably the same root cause)

Image for reference:
![overlay2](http://i.imgur.com/dynI2sn.png)

v3.0.10

**Comment by pacmanfox** [comment]
Add a screenshot if you can and client version number. Thanks.

**Comment by softwarez** [comment]
Updated

**Comment by pacmanfox** [comment]
Merged these issues together.

**Comment by rsbmatt** [comment]
Fixed in beta, 3.0.14.3 ![image](https://user-images.githubusercontent.com/23370763/28888750-bfe080c6-778f-11e7-9c7b-c4d2b1d7acb3.png)
