### ISSUE TITLE
Experience: Reset skill counters are not removed from total pie

### ISSUE THREAD

**Issue by philtyl** [rsbmatt/OSBuddy#112]
Environment:
Version:  v3.0.13

Description:
Total Experience Tracker is showing stale values for reset skills

Reproduce:
1. Gain xp in multiple skills (skill X, Y, Z)
2. Reset tracker for skill X
3. Tracker for skill X is removed from list for total tracker keeps showing the last xp gained for skill X
4. After gaining xp for skill X the portion of the pie for skill X is reduced to the new xp gained total shown in the individual tracker

Assumed Functionality:
Resetting skill X should immediately remove skill X from the total tracker pie graph

Screenshots:
1. Before reset
![screenshot at 2017-08-02 06-58-26](https://user-images.githubusercontent.com/1184136/28870987-1256fa80-7748-11e7-9eec-167a0cf13107.png)
2. After reset
![screenshot at 2017-08-02 06-58-36](https://user-images.githubusercontent.com/1184136/28871004-1e833fa8-7748-11e7-9b39-e68fc4f905be.png)
3. After XP gain post reset
![screenshot at 2017-08-02 06-58-58](https://user-images.githubusercontent.com/1184136/28871014-2fcb0fe8-7748-11e7-8e91-1de92cd5098b.png)

**Comment by rsbfox** [comment]
This might be by design if it's intended to always show xp since client was started. But because there isn't a way to reset it without resetting plugin. I will confirm this bug for now.

**Comment by rsbmatt** [comment]
You can right click and reset the pie separately. It appears that the click area was only around the text. I've expanded it to include the area where the actual pie is.
