### ISSUE TITLE
Food Overlay: "Cooked Meat" shows health recovery of +4hp in overlay; Heals +3hp

### ISSUE THREAD

**Issue by philtyl** [rsbmatt/OSBuddy#113]
Environment:
Version: v3.0.13

Original Reporter:
@Padisha#0440 (Discord)

Observed Behavior:
![image](https://user-images.githubusercontent.com/1184136/28871539-959f0dea-774a-11e7-9765-0f6d111ce464.png)

Expected Behavior:
Should show healing as +3hp as per http://oldschoolrunescape.wikia.com/wiki/Cooked_meat

**Comment by rsbmatt** [comment]
Fixed in beta, 3.0.14.1
