### ISSUE TITLE
Client Performance: Offsets were moved and is now overlapping.

### ISSUE THREAD

**Issue by jannicklorenzen** [rsbmatt/OSBuddy#114]
![image](https://user-images.githubusercontent.com/30437792/28886008-324076f8-77b8-11e7-8731-0fe9c05ded0c.png)

OSBuddy v.3.0.14

**Comment by jannicklorenzen** [comment]
Appears to be the entire upper right area of the game world.

![image](https://user-images.githubusercontent.com/30437792/28886841-2a823f34-77bb-11e7-8cb7-144d501c64e4.png)

**Comment by rsbfox** [comment]
https://rsbuddy.com/osbuddy/patch_notes/3.0.17
