### ISSUE TITLE
Potion Overlay: Recolour Ranging Potions

### ISSUE THREAD

**Issue by rsnjames** [rsbmatt/OSBuddy#122]
![image](https://user-images.githubusercontent.com/30417381/28903518-30c5a832-77ba-11e7-96f2-5546578165dc.png)

![image](https://user-images.githubusercontent.com/30417381/28903635-e7f797b8-77ba-11e7-8799-c767276e8efc.png)

First image, there appears to be a second outline on the potion.

Second image, the amount appears to be partially hidden by the recolouring. 

@rsbmatt is it possible recolour the model instead of using an overlay? 

How to re-produce: have ranging potions of different doses in bank and "recolour ranging potions" disabled, then enable it.  

OSBuddy version: 3.0.14.

**Comment by rsbmatt** [comment]
@It is possible to change the color using the engine, as all of the potions are actually the same model... just recolored. I don't think we recolor anything using this method yet, so I'll have to investigate.

**Comment by rsbfox** [comment]
Plugin removed https://rsbuddy.com/osbuddy/patch_notes/3.0.16
