### ISSUE TITLE
OSBuddy performance issue

### ISSUE THREAD

**Issue by rsbfox** [rsbmatt/OSBuddy#123]
![image](https://user-images.githubusercontent.com/30416150/28932688-61d1c30a-7848-11e7-84ce-ee19d36cbea2.png)
![image](https://user-images.githubusercontent.com/30416150/28932773-a1f60bee-7848-11e7-9cf5-27c6c5fa3eb8.png)
![image](https://user-images.githubusercontent.com/30416150/28932755-945d63d8-7848-11e7-8146-07f85411dd03.png)

**Comment by rsbfox** [comment]
![image](https://user-images.githubusercontent.com/30416150/28932919-2a286444-7849-11e7-992b-a7f153344dda.png)

The fix for this guy.

**Comment by jannicklorenzen** [comment]
Also the fix for me and many others.

**Comment by ccarpenter04** [comment]
I'd say this is a pretty high priority change to be made to the startup arguments, even though it's not what the official Jagex launcher uses a JMod did confirm that they must have copied it unintentionally from the RS3 argument file and confirmed that they would expect no negative side effects and improved performance if it was changed (and that he would see about getting it changed in the default launching file in the future)

**Comment by rsbfox** [comment]
![image](https://user-images.githubusercontent.com/30416150/29042716-0d96f51c-7b86-11e7-8175-c4d075aa87a4.png)

This is getting done in the near future.
