### ISSUE TITLE
Clue Scrolls: Missing steps

### ISSUE THREAD

**Issue by jannicklorenzen** [rsbmatt/OSBuddy#130]
**Hard clue:**

- [x] Come have a cip with this great soot covered denizen.

Solution:

Fairy ring code: CIP

**Hard clue:**

- [x] Talk to Miner Magnus in Miscellania

Question: 

How many coal rocks around here?

Answer: 

8

**Hard clue:**

- [x] I have many arms but legs, I have just one. I have little family but my seed you can grow on, I am not dead, yet I am but a spirit, and my power, on your quests, you will earn the right to free it.

Solution:

Talk to the Spirit tree at Tree Gnome Village

Question:

What is the next number in the sequence?
1, 11, 21, 1211, 11221, 31211.

Answer:

13112221

**Hard clue:**

- [x] Rotting next to a ditch. Dig next to the fish.

Solution:

Dig next to the fish spot, east of the boat at Burgh de Rott

Tile: 3547, 3183, 0     ---     0,55,49,27,47

**Hard clue:**

- [x] 'A bag belt only?' he asked his balding brothers.

Solution:

Talk to Abbot Langley at the Edgeville Monastery

**Hard clue:**

- [x] When no weapons are at hand, then is the time to reflect. In Saradomin's name, redemption draws closer...

Solution:

Search the drawers in the room with the Glassblowing pipe (south wall) in Entrana

**Hard clue:**

- [x] He knows just how easy it is to lose track of time.

Solution:

Talk to Brother Kojo at the Clocktower south of Ardougne

Question: 

On a clock, how many times a day do the minute hand and the hour hand overlap?

Answer: 

22

NPC ID = 3606

**Hard clue:**

- [x] Leader of the Yak City.

Solution:

Talk to Mawnis Burowgar in Neitiznot 

NPC ID = 1879

**Hard clue:**

- [x] The mother of the reptilian sacrifice.

Solution:

Talk to Zul-Cheray at Zul-Andra

NPC ID = 2035

**Hard clue:**

- [x] In the city where merchants are said to have lived, talk to a man with a splendid cape, but a hat dropped by goblins.

Solution:

Talk to the Head chef in the Cooks' guild in Varrock.

NPC ID = 2658

**Hard clue:** 

- [x] Between where the best are commemorated for a year, and a celebratory cup, not just for beef.

Solution:

Dig next to the clan cup trophy at the clan wars.

**Hard clue:**

- [x] THEY'RE EVERYWHERE!!!! But they were here first. Dig for treasure where the ground is rich with ore.

Solution:

Dig next to the entrance of Security of Stronghold in Barbarian Village.

**Easy clue:**

- [x] I would make a chemistry joke, but I'm afraid I wouldn't get a reaction.

Solution:

Talk to the Chemist in Rimmington

NPC ID = 1146

**Comment by rsbfox** [comment]
Drunken dwarf at keldagrim step doesn't highlight him //from mate

**Comment by rsbmatt** [comment]
Most of these clues are already in the client. I need to look into why the answers don't always display.

I checked off a few that I updated the coordinates/added to the client.

**Comment by rsbmatt** [comment]
Few more of these have been corrected.
