### ISSUE TITLE
Mouse keys: Add option for Numpad 0 to act like shift when clicking

### ISSUE THREAD

**Issue by rsbfox** [rsbmatt/OSBuddy#134]
This was workaround I suggested to Matthew for windows users.

Not really a bug but on Windows only you cannot hold shift key and use mouse keys because windows hijacks the shift first and turns numpad into arrow keys.

**Comment by rsbfox** [comment]
Update: This is possible to do. OSBuddy can tell osrs shift key was pressed when user hits numpad 0. Then windows never sees a real shift key and switches numlock off.

**Comment by rsbmatt** [comment]
Fixed in beta, v3.0.15.5
