### ISSUE TITLE
macOS app has some problems

### ISSUE THREAD

**Issue by rsbfox** [rsbmatt/OSBuddy#140]
- [ ] Trying to use system Java.

![image](https://user-images.githubusercontent.com/30416150/28998353-a37f473c-79f6-11e7-902a-268abf67f476.png)

I assume this is from running a java command to relaunch after loader update/forking new osbuddy.
Would checking java.home get you directory of java executable inside app bundle?
Or I guess could use com.apple.eio.FileManager.getPathToApplicationBundle() for everything.

Also was this linking issue ever found and fixed?

- [ ] Linking issue. Likely fixed by using whole jdk folder from jetbrains.
`Exception in thread "main" java.lang.UnsatisfiedLinkError: /Applications/OSBuddy.app/Contents/PlugIns/jdk1.8.0.jdk/Contents/Home/jre/lib/libawt.dylib: dlopen(/Applications/OSBuddy.app/Contents/PlugIns/jdk1.8.0.jdk/Contents/Home/jre/lib/libawt.dylib, 1): Library not loaded: /System/Library/Frameworks/JavaVM.framework/Versions/A/Frameworks/JavaNativeFoundation.framework/Versions/A/JavaNativeFoundation`

- [ ] When it relaunches itself it looks like a plain jar being ran. Could set -Xdock:icon and -Xdock:name

- [ ] Icon was not added to app correctly. App still has Orion.icns file. Even though plist mentions OSBuddy.icns (does not exist).
Someone just pasted icon into `get info` creating an `Icon?` file that overrides the broken app icon.
![image](https://user-images.githubusercontent.com/30416150/29706080-8ffae65a-894e-11e7-9f05-99e4d00fa724.png)

- [ ] hidpi issue from plist having these set to true. #201 
![image](https://user-images.githubusercontent.com/30416150/29706282-51d1d054-894f-11e7-8648-e8033692e4db.png)

- [ ] Out of date Java causing some performance issues with mouse #78 and this bug.
![image](https://user-images.githubusercontent.com/30416150/29706335-91e49cd0-894f-11e7-9b91-86718b3bc65b.png)

- [ ]  App translocation is breaking osbuddy on macOS. Packaged as a dmg with arrow pointing to Applications folder alias would get many more users to install it properly.

**Comment by rsbfox** [comment]
Another issue this would fix is problem when user has installed Java 9.
It will still try to relaunch using system Java instead of Java in plugin folder. Including with default arguments. -Xinc makes it fail.

```
The loader channel is JAR
Signature was good for the loader, saving it into the updates folder
Executing new loader
exit value is 0
```

**Comment by pacmanfox** [comment]
Also App translocation is breaking osbuddy on macOS. Packaged as a dmg with arrow pointing to Applications folder alias would get many more users to install it properly.

**Comment by rsbfox** [comment]
New app covers most of this.
