### ISSUE TITLE
Clue Scroll : Jig at Jiggig. 

### ISSUE THREAD

**Issue by UhWatchMe** [rsbmatt/OSBuddy#143]
Wrong location
-
![Image of wrong location](http://i.imgur.com/uw9U7Nc.png)
![Image of wrong location world map](http://i.imgur.com/2snN7Ut.png)
Correct location (2477, 3047)
-
![Image of good location](http://i.imgur.com/MAQGxv3.png)

**Comment by 0tna** [comment]
Tile Location is: 2477, 3047
- [![Screenshot from Gyazo](https://gyazo.com/501292fc485582f7eaea3988ce6630cf/raw)](https://gyazo.com/501292fc485582f7eaea3988ce6630cf)

**Comment by rsbmatt** [comment]
Fixed in beta, v3.0.15.3
