### ISSUE TITLE
Clue Scroll : 16 degrees 43 minutes north 30 degrees 1 minute west

### ISSUE THREAD

**Issue by UhWatchMe** [rsbmatt/OSBuddy#149]
## **Map gives wrong location**
![Image of wrong location](https://media.discordapp.net/attachments/187952922699628544/344179183355953155/unknown.png?width=596&height=233)

## **Correct location** (1478, 3695)
![Image of correct location](https://cdn.discordapp.com/attachments/187952922699628544/344179480899878914/unknown.png)

**Comment by 0tna** [comment]
- Correct Location: 1478, 3695 (osbuddy tile location)

**Comment by rsbfox** [comment]
Report that client crashes.

**Comment by rsbfox** [comment]
Fixed in next release.
