### ISSUE TITLE
Special Attack Orb: Incorrect position

### ISSUE THREAD

**Issue by rsbfox** [rsbmatt/OSBuddy#15]
v3.0.10

Workaround is switch to fixed mode and back to resizable.

**Comment by rsbfox** [comment]
![image](https://user-images.githubusercontent.com/30416150/28675931-4af121bc-72b7-11e7-94f4-db35a1834972.png)
v3.0.12 (not me)

**Comment by rsbfox** [comment]
Will assume this was fixed for now.

**Comment by rsbfox** [comment]
This isn't fixed v3.0.19

**Comment by rsbmatt** [comment]
Looks fixed since 3.0.20

**Comment by rsbfox** [comment]
Bug exists 3.0.21

https://mobile.twitter.com/FlaafenFlaaf/status/909933251678146560

**Comment by rsbmatt** [comment]
This bug report better stay dead now.
