### ISSUE TITLE
Option Reorder: Left click pickpocket ham members

### ISSUE THREAD

**Issue by rsbfox** [rsbmatt/OSBuddy#150]
Suggested by Zlapperino#9010
-
![image](https://user-images.githubusercontent.com/30416150/29039792-b43d5cb4-7b7a-11e7-915a-4f9c8c8e3c73.png)
![image](https://user-images.githubusercontent.com/30416150/29039894-19d7d6da-7b7b-11e7-8983-d32cf4d4b0c5.png)

Let me know if this isn't allowed and I will let him know.

**Comment by ThanksRSB** [comment]
I think you could get away with doing it on HAM members. Good for easy clues
