### ISSUE TITLE
Clue Scroll : anagram Brambickle wrong location on map

### ISSUE THREAD

**Issue by woltiw** [rsbmatt/OSBuddy#151]
The location for the npc "Brambickle" should be on Trollweiss mouintain, but the maps shows a location south-west of the Khazari Jungle (in the water).
![2017-08-07 21_02_32-start](https://user-images.githubusercontent.com/15696227/29041673-1145ce9e-7bb4-11e7-958c-62ad016b2c4c.png)

**Comment by UhWatchMe** [comment]
https://www.youtube.com/watch?v=8j0m75oiG5U (Location since it's not on the Wiki according to Woltiw).

**Comment by 0tna** [comment]
Npc ID = 2551
npc tile location = 2783, 3861  *Picked a random tile in the middle of his roaming area*

**Comment by rsbmatt** [comment]
Fixed in beta, v3.0.15.3
