### ISSUE TITLE
Bank Overlay: Infernal Tools are not exchangeable and should have 0 value

### ISSUE THREAD

**Issue by rsbfox** [rsbmatt/OSBuddy#154]
![image](https://user-images.githubusercontent.com/30416150/29071196-7890f3a6-7c10-11e7-9184-53c6f1a460d2.png)
![image](https://user-images.githubusercontent.com/30416150/29071200-8365e64c-7c10-11e7-8ffd-bf45bf3f1ade.png)

#22 
> Only suggest untradeable items that can be converted into something with value easily. Items like infernal tools can never be converted back to something that can be sold on ge. So while they had a cost, they don't have a value anymore.

Please ignore people that just want their total bank value to go up. This is ge value for all plugins to check.  ![image](https://user-images.githubusercontent.com/30416150/29071328-134ec0c6-7c11-11e7-98fb-b2ce6e6c3537.png)

An item that cannot be made exchangeable cannot have a GE value.

**Comment by rsbmatt** [comment]
Fix is ready
