### ISSUE TITLE
Clue Scroll : Shrug in the Zamorak Temple found in the Eastern Wilderness.

### ISSUE THREAD

**Issue by UhWatchMe** [rsbmatt/OSBuddy#158]
# **Clue scroll**
![Image of clue scroll](http://i.imgur.com/7uq8nkP.png)

# **Given location (which is wrong)**
![Image of location which is wrong](http://i.imgur.com/Ae1upKX.png)

# **Correct location and tile** 
![Image of correct location and tile](http://i.imgur.com/Lpm1TbW.png)
#**Image from OSRS Wiki**
![Image Wiki](https://vignette3.wikia.nocookie.net/2007scape/images/3/30/Emote_clue_-_shrug_zamorak_temple_wilderness.png/revision/latest?cb=20160802143033)

**Comment by 0tna** [comment]
Correct Location: 3239, 3611, 0
picture of the location if needed, https://prnt.sc/g6gtj0

**Comment by UhWatchMe** [comment]
Confirmed in 3.0.19 to be working

![image of world map](http://i.imgur.com/FCKRPX5.png)
![image of in game](http://i.imgur.com/jttnzFu.png)
