### ISSUE TITLE
Option Reorder: Inconsistently broken swaps

### ISSUE THREAD

**Issue by jannicklorenzen** [rsbmatt/OSBuddy#161]
Option reorder is broken by random it seems. What _will_ break the option reorder (functionality-wise, visually it doesn't change) is to press "Reset" in the Option Reorder plugin.

https://gfycat.com/VictoriousMagnificentBarnswallow

Also Xeric's Talisman is possesed.

https://gfycat.com/ShadyQueasyBlackandtancoonhound

OSBuddy v.3.0.17

**Comment by NoEffex** [comment]
So the solution is going to be to whitelist which jewelry to reorder. So far we have

- Amulet of glory
- Skills necklace
- Combat bracelet
- Ring of wealth 
- Ring of duelling
- Games necklace
- Slayer ring

Xeric's Talisman will need more looking into because it must have the order of the options in a funny way.

**Comment by rsbfox** [comment]
In reply to the first part of the issue. I'm not sure how dynamic option swapping is. Like I think some changes need a relog to apply.

For the whitelist from #76 
- [ ] Necklace of passage
> Necklace of passage(5)#21146
> Necklace of passage(4)#21149
> Necklace of passage(3)#21151
> Necklace of passage(2)#21153
> Necklace of passage(1)#21155
- [ ] Ring of returning
> Ring of returning(5)#21129
> Ring of returning(5)#21132
> Ring of returning(5)#21134
> Ring of returning(5)#21136
> Ring of returning(5)#21138
- [ ] Burning amulet
> Burning amulet(5)#21166
> Burning amulet(4)#21169
> Burning amulet(3)#21171
> Burning amulet(2)#21173
> Burning amulet(1)#21175

**Comment by rsbfox** [comment]
As for talisman, the only difference I see is "Rub" is option 2 instead of 3 like most items.
```
{
    "id": 13393,
    "name": "Xeric\u0027s talisman",
    "exchangeable": false,
    "placeholder_id": 18465,
    "values": {
      "value_store": 351,
      "alchemy_high": 210,
      "alchemy_low": 140
    },
    "actions": {
      "inventory": {
        "1": "Wear",
        "2": "Rub",
        "3": "Check",
        "4": "Uncharge"
      }
    },
    "parameters": {
      "451": "Xeric\u0027s Look-out",
      "452": "Xeric\u0027s Glade",
      "453": "Xeric\u0027s Inferno",
      "454": "Xeric\u0027s Heart",
      "455": "Xeric\u0027s Honour",
      "456": "Check"
    }
  },
```

Edit: Slayer ring is the only other item with "Rub" as option 2 and it has same glitch.
Same with Eternal ring if you could whitelist that as well.

- [ ] "id": 21268, "name": "Slayer ring (eternal)",
