### ISSUE TITLE
Clue Scroll : Come to the evil ledge, Yew know yew want to. Try not to get stung.

### ISSUE THREAD

**Issue by UhWatchMe** [rsbmatt/OSBuddy#165]
# **Clue scroll**
![Image of clue](http://i.imgur.com/ca2XizO.png)

# **Location of clue where to dig in Edgeville**
![Image of clue dig location](http://i.imgur.com/e7HLB8A.png)

**Comment by 0tna** [comment]
Osbuddy tile location: 3089, 3468, 0
