### ISSUE TITLE
Fishing: Karambwan and karambwanji support

### ISSUE THREAD

**Issue by jannicklorenzen** [rsbmatt/OSBuddy#168]
- [ ] Karambwan

 spots. There's 2 instances of #4712 for some reason.
Note: these spots might work a bit differently than normal fishing spots.

![image](https://user-images.githubusercontent.com/30437792/29243497-aaaa2cf2-7fa0-11e7-8029-e05f30aa3fee.png)

- [ ] Karambwanji

 spots are all #4710

![image](https://user-images.githubusercontent.com/30437792/29243512-d3c1370c-7fa0-11e7-9ceb-7db26328cb69.png)

**Comment by rsbfox** [comment]
https://rsbuddy.com/osbuddy/patch_notes/3.0.18
