### ISSUE TITLE
Clue Scroll : Must be full of railings.

### ISSUE THREAD

**Issue by UhWatchMe** [rsbmatt/OSBuddy#174]
# **Clue Scroll**

![image of clue](http://i.imgur.com/9EDInda.png)

# **The problem**

Apperently it draw the walls also which is not needed only the boxes as in the screenshot below.
![image of boxes](http://i.imgur.com/9qc53G4.png)

**Comment by 0tna** [comment]
Boxes ID (6176)
Boxes Location: 2576, 3464, 0
