### ISSUE TITLE
Clue Scroll : Beckon on the east coast of the Khazari Jungle. Beware of double agents! Equip any vestment stole and a heraldic rune shield.

### ISSUE THREAD

**Issue by UhWatchMe** [rsbmatt/OSBuddy#175]
# **Clue scroll**

![image of clue](http://i.imgur.com/5hZleBx.png)

It says ANY stole and Heraldic rune shield but it in the left corner it says bandos stole the most expensive one. Might do the cheapest same as Heraldic shield?

# **Wrong location**
![image of wrong location](http://i.imgur.com/VjntrKV.png)

# **Correct location**
![image of correct location](http://i.imgur.com/N0HfHoP.png)
![image of world map correct location](http://i.imgur.com/XYVRVDZ.png)

**Comment by 0tna** [comment]
Tile location: 2954, 2933, 0
