### ISSUE TITLE
Clue Scroll : This village has a problem with cartloads of the undead. Try checking the bookcase  to find the answer.

### ISSUE THREAD

**Issue by UhWatchMe** [rsbmatt/OSBuddy#176]
# **Clue Scroll**
![image of clue](http://i.imgur.com/oleof2Z.png)

The world map does not work, the tip is correct though also does not overlay the bookcase as shown below.

# **The bookcase in Shilo Village**
![bookcase](http://i.imgur.com/8rd566L.png)

# **Location world map**
![World map location](http://i.imgur.com/y2pr2Cg.png)

**Comment by 0tna** [comment]
Bookcase ID (394)
Bookcase location (2833, 2992, 0)
