### ISSUE TITLE
Clue Scroll : When no weapons are at hand, then is the time to reflect. In Saradmin's name, redemption draws closer...

### ISSUE THREAD

**Issue by UhWatchMe** [rsbmatt/OSBuddy#178]
# **Clue scroll**
![clue](http://i.imgur.com/q8y1ZoA.png)

It does not show on the world map but the screenshot below is the location on Entrana (no weapons or armor allowed no requirements except the Lost City Quest (?))

# **World map location**
![world map location](http://i.imgur.com/aEKQVVH.png)

# **Drawers to search**
![drawers](http://i.imgur.com/LBBmc9E.png)

**Comment by 0tna** [comment]
Drawers ID (350)
Drawers location, 2818, 3351, 0
