### ISSUE TITLE
OpenGL: Reply with monster clickboxes that are too large

### ISSUE THREAD

**Issue by hctim852** [rsbmatt/OSBuddy#18]
v3.0.10

In OpenGL, some monsters have clickboxes that extend way past their model, or are much larger than without OpenGL.

- [x] Brutal Black Dragons
- [x] Lighthouse Dagganoths (and probably others)
- [x] Black Demons
- [x] Greater Demons
- [x] Vorkath

**Comment by azeruk** [comment]
Black demons

**Comment by hctim852** [comment]
Jad Pet (and maybe others)

**Comment by hctim852** [comment]
Skoitzo pet

**Comment by rsbfox** [comment]
Vorkath
