### ISSUE TITLE
Clue Scroll : B I P 7 0 1 3

### ISSUE THREAD

**Issue by UhWatchMe** [rsbmatt/OSBuddy#180]
# **Clue scroll**
![clue](http://i.imgur.com/FObxx1z.png)

# **Tile to dig also missing required items spade fairy ring coce BIP**
![tile](http://i.imgur.com/x6wV5Wk.png)

**Comment by 0tna** [comment]
Osbuddy Tile location: 3407, 3330, 0
Required item: Spade (ID 952)
