### ISSUE TITLE
Option Reorder: Options switching places constantly.

### ISSUE THREAD

**Issue by jannicklorenzen** [rsbmatt/OSBuddy#183]
Some users are having issues with the Option Reorder plugin yet again. Specifically the Tool Leprechauns and the normal + eternal slayer ring.

Grand Exchange clerks and bankers might also have this issue (can't replicate any of this on my 2 setups).

Also, the options will stay switched when you disable the plugin (without reloading client).

Haven't been able to pin down the cause of the bug, but I believe the speed of the options switching are related to your framerate.

https://gfycat.com/UnfinishedUnselfishBlacklemur

OSBuddy v3.0.18

**Comment by rsbfox** [comment]
Update to say jewlery option is still breaking slayer ring. v3.0.20
