### ISSUE TITLE
Clue Scroll : Laugh in Jokul's tent in the Mountain Camp. Beware of double agents! Equip a rune full helmet, blue dragonhide chaps and a fire battlestaff.

### ISSUE THREAD

**Issue by UhWatchMe** [rsbmatt/OSBuddy#188]
# **Clue scroll**
![Clue scroll](http://i.imgur.com/jDSXA4b.png)

# **Wrong location on world map**
![Wrong world map](http://i.imgur.com/jRDlSwe.png)

# **Good location and tile closest Fairy Ring is AJR also required to have done Mountain Daughter Quest to acces the area.**
![Good location and tile](http://i.imgur.com/oNgPYCt.png)
![On the world map](http://i.imgur.com/t2F79BQ.png)

**Comment by 0tna** [comment]
OSB Tile: 2812, 3681, 0
