### ISSUE TITLE
Clue Scroll : Falo the bard wants to see you.

### ISSUE THREAD

**Issue by UhWatchMe** [rsbmatt/OSBuddy#189]
# **Clue scroll**
![clue](http://i.imgur.com/3Kab5Qt.png)

# **Falo the bard and world map location north of Seers' Village**
![Falo](http://i.imgur.com/bTMGnpe.png)
![world map](http://i.imgur.com/ri3B6qq.png)

**Comment by 0tna** [comment]
NPC ID (7306)
Tile  2689, 3549, 0 Note, this is the player tile. you can't stand on the npc tile. if you want the npc tile it's most likely 2689, 3550, 0

i assume a hint could be added to this clue scroll as well. something like

"Hint: You can find Falo the Bard North of Seers' Village."
