### ISSUE TITLE
Clue Scroll : His head might be hollow, but the crates nearby are filled with suprises.

### ISSUE THREAD

**Issue by UhWatchMe** [rsbmatt/OSBuddy#190]
# **Clue Scroll**

![clue](http://i.imgur.com/e4MAcwI.png)

# **Wrong crate the one with the magnify glass is correct**
![bad crate and good crate](http://i.imgur.com/xI3HvkR.png)

A simple gif to show it.
![Gif](http://i.imgur.com/ddjRXuN.gif)

**Comment by 0tna** [comment]
Crate ID's are both 354 
the correct crate is on Tile 3478, 3091, 0
