### ISSUE TITLE
Clue Scroll : D K S 2 3 1 0

### ISSUE THREAD

**Issue by UhWatchMe** [rsbmatt/OSBuddy#191]
# **Clue scroll**
![clue](http://i.imgur.com/yp5HwDD.png)

# **Tile to dig also missing required item spade also not able to show on world map**
![tile](http://i.imgur.com/27gf4xG.png)

**Comment by 0tna** [comment]
OSB Tile: 2747, 3720, 0
Required item: Spade (ID 952)

**Comment by UhWatchMe** [comment]
![clue](http://i.imgur.com/4jsXpmH.png)
![ingame](http://i.imgur.com/vE0NMqZ.png)

Does not work, no tile overlay or anything. August 26 2017.

**Comment by UhWatchMe** [comment]
![widget](https://i.imgur.com/0ClHPdx.png)
