### ISSUE TITLE
Clue Scroll : Search the crate in the left-hand tower of Lumbridge Castle.

### ISSUE THREAD

**Issue by UhWatchMe** [rsbmatt/OSBuddy#194]
# **Clue scroll**
![clue](http://i.imgur.com/5Qa66tl.png)

# **Correct location and tile in Lumbridge**
![correct location and tile](http://i.imgur.com/hQtNgry.gif)

**Comment by 0tna** [comment]
Crate ID: 357
Crate Location: 3228, 3212, 1

**Comment by UhWatchMe** [comment]
![picture](https://i.imgur.com/MWsSjLo.png)

Still not working 19-11-2017.

**Comment by rsbmatt** [comment]
@xNonCombat next time you get this can you get the exact text of the clue from the Widget explorer... I just pushed something that _might_ fix it. Close this if it is fixed.

**Comment by UhWatchMe** [comment]
@rsbmatt Sure is that with all clue's or only with this one?
