### ISSUE TITLE
Clue Scroll : I wonder how many bronze swords he has handed out.

### ISSUE THREAD

**Issue by UhWatchMe** [rsbmatt/OSBuddy#195]
# **Clue Scroll**
![clue](http://i.imgur.com/xgRkGAR.png)
# **Correct location at Edgeville Dungeon talk to Vannaka the Slayer Master**
![correct](http://i.imgur.com/cy6oMNw.png)
# **Hint missing**
The hint is missing it could be "A Slayer master in the Edgeville Dungeon".

**Comment by 0tna** [comment]
NPC ID: 403
Add hint: A Slayer master in the Edgeville Dungeon

**Comment by 0tna** [comment]
OSB Tile: 2073, 4846, 0
Items Needed:
Spade - 952
Dramen Staff - 772
