### ISSUE TITLE
Clue Scroll : C I S 0 0 0 9

### ISSUE THREAD

**Issue by UhWatchMe** [rsbmatt/OSBuddy#198]
# **Clue scroll**
![clue](http://i.imgur.com/cF72EUN.png)

# **Tile over lay is missing, world map isn't working also it costs 80k to unlock the Fairy if it's any of importance.**
![tile](http://i.imgur.com/oQvnc70.png)

**Comment by 0tna** [comment]
OSB Tile: 1630, 3868, 0
Item needed: Spade (id 952)

**Comment by rsbmatt** [comment]
Already fixed, waiting for release.

**Comment by UhWatchMe** [comment]
Not fixed as of 20 September.
![widget](https://i.imgur.com/wgbCduk.png)
