### ISSUE TITLE
Clue Scroll : Aggie I see, Lonely and southern I feel I am neither inside nor outside the house yet no house would be complete without me. Your treasure lies beneath me.

### ISSUE THREAD

**Issue by UhWatchMe** [rsbmatt/OSBuddy#200]
# **Clue Scroll (Hard)**
![clue](http://i.imgur.com/UFimrVW.png)

# **Correct location**
![tile](http://i.imgur.com/Pu4mC0n.png)
![worldmap](http://i.imgur.com/7I5zoxa.png)

# **Items required**
A Spade 

# **Hint missing**
Dig outside the window of Aggie the Witch's house in Draynor Village. (From Wiki)

**Comment by 0tna** [comment]
OSB Tile: 3085, 3255, 0
Item needed: Spade (id 952)
add hint: "Dig outside the window of Aggie the Witch's house in Draynor Village."
