### ISSUE TITLE
Clue Scroll : The cheapest water for miles around, but they react badly to religious icons.

### ISSUE THREAD

**Issue by UhWatchMe** [rsbmatt/OSBuddy#202]
# **Clue Scroll (Hard)**
![clue](http://i.imgur.com/xiejAcG.png)

# **Correct location it's missing the world map also**
![worldmap](http://i.imgur.com/tkJnK4s.png)
![the crate](http://i.imgur.com/I8ZRgFf.png)

**Comment by 0tna** [comment]
Crate ID: 354 
Crate Location: 3178, 2987, 0
