### ISSUE TITLE
Clue Scroll : C K P 0 2 2 4

### ISSUE THREAD

**Issue by UhWatchMe** [rsbmatt/OSBuddy#203]
For some reason the image tag didn't work.

# **Clue Scroll (Hard)**

http://i.imgur.com/aN0w8tg.png

# **Correct location CKP Fairy Ring**

http://i.imgur.com/ewcZ1l6.png

# **Requirements**
- A spade 
- Dramen Staff (?)
- Quest Fairy Tale 2

**Comment by 0tna** [comment]
OSB Tile: 2073, 4846, 0
Items Needed:
Spade - 952
Dramen Staff - 772

**Comment by rsbmatt** [comment]
Should be going out today

**Comment by UhWatchMe** [comment]
Still broken as of 28 August 2017

![clue](http://i.imgur.com/BxBkMQ6.png)
![ingame](http://i.imgur.com/mau9Ian.png)

**Comment by hctim852** [comment]
Just got this and it's still broken as if Sept 6th. Saw it was on the 3.0.21 milestones, but it didn't go out.
