### ISSUE TITLE
Clue Scroll : Buried beneath the ground, who knows where it's found. Lucky for you, A man called Jorral may have a clue.

### ISSUE THREAD

**Issue by UhWatchMe** [rsbmatt/OSBuddy#204]
# **Clue Scroll (Master)**
![clue](http://i.imgur.com/1Z8uWZI.png)

# **Correct location**
![worldmap](http://i.imgur.com/xQ7GKEI.png)
![Jarrol](http://i.imgur.com/ubqNbrY.png)

# **Hint missing**
Speak to Jorral to receive a strange device, which works similarly to the enchanted key. (From the Wiki)

# **Requirements**

- Completed the Quest [Making History](http://oldschoolrunescape.wikia.com/wiki/Making_History)

**Comment by 0tna** [comment]
NPC ID: 3490

**Comment by rsbfox** [comment]
Reported broken 3.0.20

**Comment by UhWatchMe** [comment]
Had this yesterday can't click world map so it won't add, but it was reported fixed. 

![clue](http://i.imgur.com/OzCzIVD.png)

**Comment by rsbmatt** [comment]
Fixed.
