### ISSUE TITLE
Clue Scroll : B L P 6 2 0 0

### ISSUE THREAD

**Issue by UhWatchMe** [rsbmatt/OSBuddy#205]
# **Clue Scroll (Hard)**
![clue](http://i.imgur.com/kPbqJe1.png)

# **Correct location**
![tile](http://i.imgur.com/g6COoHq.png)
![worldmap](http://i.imgur.com/ebt7k44.png)

# **Required items**
- A Spade

**Comment by 0tna** [comment]
OSB Tile: 2439, 5132, 0
Item Needed: Spade (ID 952)

**Comment by UhWatchMe** [comment]
The clue does not work as of 26 August 2017.
Also required items interface.
![clue](http://i.imgur.com/NAJQu1p.png)
![game](http://i.imgur.com/FtQxVpx.png)

**Comment by UhWatchMe** [comment]
![widget](https://i.imgur.com/JkgLTf0.png)
