### ISSUE TITLE
Clue Scroll : Come have a cip with this great soot covered denizen.

### ISSUE THREAD

**Issue by UhWatchMe** [rsbmatt/OSBuddy#206]
# **Clue Scroll (Hard)**
![clue](http://i.imgur.com/lncEzLs.png)

# **Correct location**
![npc](http://i.imgur.com/S5RCol1.png)
![worldmap](http://i.imgur.com/zD9cvl9.png)

# **Hint missing**
Talk to Miner Magnus east of the fairy ring (code cip).
Answer: 8 (From the Wiki)

**Comment by 0tna** [comment]
NPC ID: 3654
Answer: 8 
Fairy ring code: CIP
