### ISSUE TITLE
Clue Scroll : Panic in the heart of the Haunted Woods.

### ISSUE THREAD

**Issue by UhWatchMe** [rsbmatt/OSBuddy#208]
# **Clue Scroll (Hard)**
![clue](http://i.imgur.com/TQcKf02.png)

# **Giving wrong location, also no Hint also giving the Required Emote Items while none is required.**
![wrong location](http://i.imgur.com/073hgkm.png)

# **Correct location**
![tile](http://i.imgur.com/ZFQcF9M.png)
![worldmap](http://i.imgur.com/QPkUBII.png)

# **Hint missing**
Hint From Wiki - The location is east of the Fairy ring ALQ in the Haunted Woods. Players should be careful of the Vampires summoned by the spider roaming around that area.

**Comment by 0tna** [comment]
OSB Tile: 3611, 3492, 0

**Comment by UhWatchMe** [comment]
As of August 26 2017 I got the clue again

![clue](http://i.imgur.com/EBNIMhm.png)

It's missing the Hint and the Required Item Overlay is not needed since you need to un-equip any worn items.

The rest works perfect! :)
