### ISSUE TITLE
OpenGL: Issue with elevated areas / Reply with more as they are found

### ISSUE THREAD

**Issue by hctim852** [rsbmatt/OSBuddy#21]
v3.0.10

Afaik, due to where OpenGL renders the floor layer, it makes some places unclickable. This applies especially for raised areas compared to surroundings. 

Known areas:
- [x] Taverley dungeon slayer exclusive area
- [x] Pest control void knight platform (while in game, not on dock)
- [x] Deathly Mansion POH style
- [x] Raids area cobblestone and inside tents
- [x] Any boat when below deck
- [x] Asgarnian dungeon wyvern slayer exclusive
- [x] [Some docks](https://fat.gfycat.com/UntimelyUnlinedDeermouse.webm)

**Comment by rsbfox** [comment]
Fix ready.
