### ISSUE TITLE
Timer Manager : Warning Mode - Flash Screen

### ISSUE THREAD

**Issue by UhWatchMe** [rsbmatt/OSBuddy#217]
This got reported by Scrotumbeard.

The flash screen does not work, however the Flash Icon and Flash Timer are working perfectly.

Also tested it myself.

**Comment by UhWatchMe** [comment]
Update it does work, but it's not really notice-able I was expecting the whole screen and not the edges.

**Comment by 0tna** [comment]
Closed on request.
