### ISSUE TITLE
Clue scroll : Panic on the Wilderness volcano bridge.

### ISSUE THREAD

**Issue by UhWatchMe** [rsbmatt/OSBuddy#231]
# **Clue Scroll (Hard)**
![clue](http://i.imgur.com/mxy3ZuY.png)

# **Location it gives which is wrong**
![wrong](http://i.imgur.com/JZal4Wx.png)

# **Correct location**
![game](http://i.imgur.com/DJdVzPp.png)
![worldmap](http://i.imgur.com/I7qQbbU.png)

# **Required items bug**

It has static items, but ANY crozier or headband works this is why I think this happens.
![requireditemsbug](http://i.imgur.com/7rvyY30.gif)

- Headbands ID's

- Red headband (2645)
- Black Headband (2647)
- Brown headband (2649)

For some readon there these three above have also the ID's below, someone has to confirm which is correct since I don't have tester using items.json file from @rsbmatt 

- Red Headband (10768)
- Black headband (10770)
- Brown headband (10772)
- White headband (12299)
- Blue headband (12301)
- Gold headband (12303)
- Pink headband (12305)
- Green headband (12307)

- All the croziers

- Saradomin crozier (10440)
- Guthix crozier (10442)
- Zamorak crozier (10444)
- Ancient crozier (12199)
- Armadyl crozier (12263)
- Bandos crozier (12275)

# **Hint missing**
The Wilderness Volcano is located in the north-east corner of the Wilderness. (Wiki)

**Comment by 0tna** [comment]
osb tile: 3368, 3935, 0
