### ISSUE TITLE
Clue scroll : Bow at the top of the lighthouse. Beware of double agents!

### ISSUE THREAD

**Issue by UhWatchMe** [rsbmatt/OSBuddy#234]
# **Clue Scroll (Hard)**
![clue](http://i.imgur.com/p64siiX.png)

# **Correct location**
![game](http://i.imgur.com/Z93Mwk5.png)
![worldmap](http://i.imgur.com/LGQBPVy.png)

# **Wrong location**
![wrong](http://i.imgur.com/kB4TlzZ.png)

# **Hint missing**
Must have repaired the Lighthouse lighting mechanism in the Horror from the Deep quest to access. The fairy ring code ALP teleports you right outside the Lighthouse. (Wiki)

**Comment by 0tna** [comment]
tile loc: 2511, 3641, 2
