### ISSUE TITLE
Clue Scroll : Blow a raspberry in the Fishing Guild bank.

### ISSUE THREAD

**Issue by UhWatchMe** [rsbmatt/OSBuddy#237]
# **Clue Scroll (Hard)**
![clue](http://i.imgur.com/bcjxnvr.png)

# **Wrong location**
![wrong](http://i.imgur.com/IfgU8YT.png)

# **Correct location**
![game](http://i.imgur.com/wgdbmae.png)
![worldmap](http://i.imgur.com/NDg8Meq.png)

# **Hint missing**
A Skills necklace for quick access to the Fishing Guild.

**Comment by 0tna** [comment]
Tile loc: 2588, 3419, 0
