### ISSUE TITLE
Clue Scroll : If you look closely enough, it seems that the archers have lost more than their needles.

### ISSUE THREAD

**Issue by UhWatchMe** [rsbmatt/OSBuddy#243]
# **Clue Scroll(Hard)**
![clue](http://i.imgur.com/VaQjEy1.png)

# **Correct location**
![game](http://i.imgur.com/pgSslXh.png)
![worldmap](http://i.imgur.com/KFwmSFm.png)

**Comment by 0tna** [comment]
Haystack id: 300
Haystack loc: 2672, 3416, 0
