### ISSUE TITLE
Clue Scroll : You'll need to look for a town with a central fountain. Look for a locked chest in the town's chapel.

### ISSUE THREAD

**Issue by UhWatchMe** [rsbmatt/OSBuddy#244]
# **Clue Scroll (Medium)**
![clue](http://i.imgur.com/52331WL.png)

# **Correct location**
![game](http://i.imgur.com/VtCYtJV.png)
![worldmap](http://i.imgur.com/LDAuFGK.png)

# **Chest to search is not overlayed or on map**
![game](http://i.imgur.com/XlgYG3b.png)
![worldmap](http://i.imgur.com/4vJxbWv.png)

**Comment by 0tna** [comment]
chest id: 5108
chest loc: 3256, 3487, 0

**Comment by UhWatchMe** [comment]
Well, now shows the chest in Varrock Church but first you have to kill a monk which it is not showing when clicking world map.
![pic](https://i.imgur.com/eh2uack.png)

Though on screen, the monks are overlayed.
![pic](https://i.imgur.com/7HXyz3w.png)

**Comment by rsbmatt** [comment]
There is only support for showing one area at the moment. It was decided that the chapel was the best place to show the marker, since the text solution said to go to the ardy monastery.
