### ISSUE TITLE
Clue Scroll : Yawn in the rogues' general store. Beware of double agents!

### ISSUE THREAD

**Issue by UhWatchMe** [rsbmatt/OSBuddy#246]
# **Clue Scroll (Hard)**
![clue](http://i.imgur.com/ZTpGjxN.png)

# **Wrong location**
![wrong](http://i.imgur.com/iQvk5ds.png)

# **Correct location**
![game](http://i.imgur.com/sEVOU8M.png)
![worldmap](http://i.imgur.com/ksg681e.png)

# **Hint missing**
Bandit Camp general store in level 23 Wilderness, north of the Dark Warriors' Fortress. The burning amulet can take you there, but be wary of player killers and level 130 bandits. (Wiki)

**Comment by 0tna** [comment]
tile: 3026, 3701, 0
