### ISSUE TITLE
Clue Scroll : The cipher reveals who to speak: GBJSZ RVFFO

### ISSUE THREAD

**Issue by UhWatchMe** [rsbmatt/OSBuddy#247]
# **Clue Scroll**
![clue](http://i.imgur.com/TyW7cmu.png)

# **The NPC is not overlayed with text "Talk-To" shes gives a Puzzle Box**
![fairyqueen](http://i.imgur.com/lQe1Lap.png)

**Comment by rsbmatt** [comment]
https://github.com/rsbmatt/OSBuddy/issues/242
