### ISSUE TITLE
Clue Scroll : Bow on the ground floor of the Legend's guild. Equip Legend's cape, a dragon battleaxe and an amulet of glory.

### ISSUE THREAD

**Issue by UhWatchMe** [rsbmatt/OSBuddy#248]
# **Clue Scroll (Elite)**
![clue](http://i.imgur.com/M35Y70p.png)

# **Correct location**
![game](http://i.imgur.com/M4p6Hr4.png)
![worldmap](http://i.imgur.com/UrpDRw5.png)

# **Required item(s)**
- Cape of Legends (1052)
- Dragon battleaxe (1377)
- Amulet of Glory (1704)
- Amulet of Glory (1) (1706)
- Amulet of Glory (2) (1708)
- Amulet of Glory (3) (1710)
- Amulet of Glory (4) (1712)
- Amulet of Glory 5) (11976)
- Amulet of Glory 6) (11978)

# **Hint missing**
In the Legends Guild, next to the Totem. Fairy ring code BLR for quick acces to the Guild.

**Comment by 0tna** [comment]
tile: 2728, 3377, 0
