### ISSUE TITLE
Runecrafting: Profit shown not working

### ISSUE THREAD

**Issue by rsnjames** [rsbmatt/OSBuddy#25]
I've only tested it on nature runes and soul runes, but the profit isn't showing. 

OSB version 3.0.11.

**Comment by rsbfox** [comment]
@Furutze Please explain in detail. I could not get mining plugin to have any effect on profit shown being broken.

Post screenshot of both mining and runecraft settings that allow you to see profit. And inventory and equipment.

**Comment by rsbfox** [comment]
Quoting Furutze
>I forgot to add that mining the rock shortcut triggers that profit window
> Oh and show total amounts on
> And hide recources gained off

**Comment by rsbfox** [comment]
OSB-82
