### ISSUE TITLE
Clue Scroll : 01 degrees 30 minutes north 20 degrees 01 minutes east.

### ISSUE THREAD

**Issue by UhWatchMe** [rsbmatt/OSBuddy#250]
# **Clue Scroll (Hard)**
![clue](http://i.imgur.com/P95I3ev.png)
![whatfairyring](http://i.imgur.com/NEf3fwQ.png)

# **Hint missing**
Since the overlay is going over the Fairy ring code I'd suggest a hint.

"Located on a small island that can only be accessed via fairy ring code CLP." - Wiki

**Comment by rsbfox** [comment]
The plugin calculates location from the cords. It doesn't have a list of each of these to add hints to. Sorry.
