### ISSUE TITLE
Option Reorder: Settings bug

### ISSUE THREAD

**Issue by jannicklorenzen** [rsbmatt/OSBuddy#263]
Log in at GE, nothing in inventory and nothing equipped.
Open the reorder options
Enable the jewelry rub swap
close client with the settings window open.

Results in completely broken option swaps.

https://gfycat.com/WhisperedWholeBlackrussianterrier

Note: This is specific to each OSRS account for some reason.

https://gfycat.com/UntidyVapidHawk
OSBuddy v3.0.20

**Comment by UhWatchMe** [comment]
I do have that problem even with items equipped.

**Comment by jannicklorenzen** [comment]
It's a problem that is "applied" if you follow the steps in the start of the report. 

Tested the steps and confirmed on 3 accounts.

**Comment by NoEffex** [comment]
The bug is triggered if you have not yet viewed your inventory, so an easy workaround until the fix is released is to just open your inventory once. I've moved the check on the inventory to inside the jewelry-specific block and that seems to have resolved it.
