### ISSUE TITLE
Clue Scroll : A L P 1 1 4 0

### ISSUE THREAD

**Issue by UhWatchMe** [rsbmatt/OSBuddy#264]
# **Clue Scroll**
![clue](http://i.imgur.com/bjoKkJb.png)

# **Correct location**
![game](http://i.imgur.com/4kddlYm.png)
![worldmap](http://i.imgur.com/kawEVYW.png)

# **Tile and map ID**

Tile ID - 2504, 3633, 0
Map ID - 2504, 12687

# **Required item(s)**
- Spade (952)

**Comment by rsbmatt** [comment]
There is something else going on with the clue scrolls that is causing them to not work, this solution is in the client.
