### ISSUE TITLE
Option Reorder: Additions

### ISSUE THREAD

**Issue by jannicklorenzen** [rsbmatt/OSBuddy#270]
There's loads of potential with this plugin, and I think it would be very beneficial to add more NPCS/Objects to this.

- [x] Swap the "Read" and "Investigate" (enter) options on the Statue of King Raedwald (catacombs entrance).

- [x] Swap the "Talk to" and "Trade" options on Charter Crewmembers. 

- [x] Swap the "Talk to" and "Pickpocket" on HAM guards in the HAM storerooms.

**Comment by UhWatchMe** [comment]
Might also do it with the following. 

- Gnome Gliders (Talk to, Travel) [Already implemented]
- Spirit tree (Talk to, Travel)
- Entrana Monks (Talk to, Travel)
- Aubrey (Talk to, Teleport)
- Zamorak Mage (Talk to, Teleport)

**Comment by Hannah-GBS** [comment]
Since this is still open, would like to see an option for this for merchants in general.
Second screening dragonhide tanning would be much less of a pain if I could just left click Ellis to Trade.

**Comment by chadronbryant** [comment]
The following UhWatchMe submitted:

Spirit tree (Talk to, Travel)
Entrana Monks (Talk to, Travel)
Aubrey (Talk to, Teleport)
Zamorak Mage (Talk to, Teleport)

Would be very nice to have to reorder.
