### ISSUE TITLE
Current boosts icon area can't be resized vertically

### ISSUE THREAD

**Issue by hctim852** [rsbmatt/OSBuddy#277]
Experienced by mBaggins#8527. 

The area for the icons cannot be sized vertically, and when it gets expanded to a large size due to lots of drained stats (e.g. KBD or basilisks w/o shield), the icons can't be moved very low due to the area being constrained to osrs window bounds. 

https://cdn.discordapp.com/attachments/177283446866051072/357187649880064010/unknown.png

**Comment by rsbmatt** [comment]
It isn't supposed to be manually resized vertically, it is supposed to be automatic... but it looks like something is wrong, I'll take a look at it soon.
