### ISSUE TITLE
Screenshot : Level up Hunter not working, others work.

### ISSUE THREAD

**Issue by UhWatchMe** [rsbmatt/OSBuddy#278]
Reported by Paw

His Hunter levels did not get captured at level up I tested it myself bought a bond for my alt to test.

Screenshot settings

![settings](https://i.imgur.com/PWf5vkI.png)

Stats 

![stats](https://i.imgur.com/BE2gFds.png)

Level up message (Slayer did work though) level up was done by Varrock Musuem thingy.

![levelup](https://i.imgur.com/R5SpC75.png)

My folder (Slayer is there).

![folder](https://i.imgur.com/uZQEDUJ.png)
![folder](https://i.imgur.com/iYV5b5b.png)

I levelled Hunter by catching Copper Bird things to ensure it is bugged
Screenshotted myself did not appear in folder.
![levelup](https://i.imgur.com/ydeh4Y1.png)
![nohunter](https://i.imgur.com/PsCgTMB.png)

**Comment by rsbmatt** [comment]
Get me the widget where the text "Your Hunter level is now __." is.

**Comment by UhWatchMe** [comment]
Ehh sure,  I'm not online today maybe someone else can. Else I'll do it as soon as I am online.

**Comment by UhWatchMe** [comment]
Here you go

![hunter](https://i.imgur.com/srxbWzd.png)

Not sure which one so here you have both

![morehunter](https://i.imgur.com/Gh797Ca.png)

Just incase any of those are wrong

![evenmorehunter](https://i.imgur.com/tsZzYkP.png)
