### ISSUE TITLE
Camera Zoom : Allow zoom control via +/- on keyboard

### ISSUE THREAD

**Issue by UhWatchMe** [rsbmatt/OSBuddy#280]
Reported by Nev

The option is enabled you are only able to press Ctrl + to zoom in but you can't zoom out with Ctrl -

I told him I'd add it to the issue tracker and got this gem 
![drop](https://i.imgur.com/rBOXcwT.png)

**Comment by rsbmatt** [comment]
Can't seem to replicate this... can you get more information, or try it yourself? Reopen it if it does not work for you.

**Comment by UhWatchMe** [comment]
![keyboard](https://imgur.com/Vl2lpTd.png)

The red arrows do allow me to zoom in and out with holding the ctrl, the black ones however don't.

**Comment by rsbfox** [comment]
Replicated bug. Added to the new tracker.
