### ISSUE TITLE
Map Clue Scroll : Search the crate in the Varrock Lumberyard.

### ISSUE THREAD

**Issue by UhWatchMe** [rsbmatt/OSBuddy#283]
# **Clue Scroll**
![clue](https://i.imgur.com/HHeR0mX.png)

# **Correct location**
![game](https://i.imgur.com/Q3kktSp.png)
![worldmap](https://i.imgur.com/qiZbzHY.png)

# **OBJECT ID**

Crate 2620 - 3309, 3503

# **Hint missing**

Search the crate inside the Lumberyard, north-east of Varrock. (Wiki)

#** Widgets**

![x](https://i.imgur.com/RqYiGy5.png)
![crate](https://i.imgur.com/e16hEwD.png)

**Comment by rsbfox** [comment]
Fixed in next release.
