### ISSUE TITLE
Screenshot : Takes screenshots at certain things in chat. Option take screenshot when level up.

### ISSUE THREAD

**Issue by UhWatchMe** [rsbmatt/OSBuddy#289]
The option "Take screenshot when level up" is the bad guy though.

![folder](https://i.imgur.com/0ngOqAP.png)
![screenshot](https://i.imgur.com/yn153Om.png)

Also takes screenshots when 

- Unnote items via bank and leprechaun
- Traveling via spirit tree
- Clue steps

I noticed they all have "You" in it, perhaps it triggers on that due the fix of Hunter screenshot? And also it has the "Click here to continu" option.

**Comment by rsbfox** [comment]
This should be fixed.
