### ISSUE TITLE
Display ping in world list

### ISSUE THREAD

**Issue by rsbfox** [rsbmatt/OSBuddy#29]
1. Does ping vary between worlds at the same location?
2. Do ICPM packets make it to actual game servers?
3. Will most players will even notice difference in ping? 
4. Would all the clients pinging worlds at same time upset Jagex?

**Comment by softwarez** [comment]
1. Should be roughly the same.
2. Yes
3. If the difference is large then yes, you could be a gametick "behind"
4. not really, the ICMP packets are really small. pretty much unnoticeable.

**Comment by rsbfox** [comment]
Okay. Seems a lot of people do ask for it.

**Comment by NoEffex** [comment]
This probably isn't feasible as Java doesn't provide ICMP functionality in it's standard library and we are always hesitant to include third-party libraries that involve native code. We could write one ourselves but the question is ultimately is it worth the time that could be spent on other features.
