### ISSUE TITLE
Cry on top of western tree in the Gnome Agility Arena

### ISSUE THREAD

**Issue by azeruk** [rsbmatt/OSBuddy#30]
Med Clue. Opening the map solution points in to west ardougne.

**Comment by rsbfox** [comment]
Hey azeruk,
Thanks for joining our issue tracker! Images are helpful for clue bugs, but not required.

**Comment by rsbfox** [comment]
> Cry on top of the western tree in the Gnome Agility Arena. Indicate 'no' before you talk to me. Equip a steel kiteshield, ring of forging, and green d'hide chaps.

Tile: (2473, 3420, 2)

**Comment by rsbmatt** [comment]
Fixed in beta, v3.0.15.3
