### ISSUE TITLE
Rune Pouch: Overlay doesn't work if the Mouseover Text plugin is disabled.

### ISSUE THREAD

**Issue by jannicklorenzen** [rsbmatt/OSBuddy#303]
Might be related to the Runecrafting pouch overlay. #304 

https://gfycat.com/ScaryScentedEnglishpointer

![gif](https://thumbs.gfycat.com/ScaryScentedEnglishpointer-size_restricted.gif)

OSBuddy v3.0.23

**Comment by UhWatchMe** [comment]
Also the "Open Rune Pouch" used to be on top, but after disabling the Mouse Over Text it goes to the bottom. Turning off "Rune Pouch" plugin and turning it back on, resolves this.
