### ISSUE TITLE
game closing when opengl is turned on 

### ISSUE THREAD

**Issue by EmilySooty** [rsbmatt/OSBuddy#308]
whenever i start the game in opengl mode it just closes itself, it happens when i log into runescape with opengl mode enabled and when i enable it in game, it just hangs there for a second and closes itself every time, i tried reinstalling java, windows runtime enviroment, the visual c++ security thing, disabling windows UAC, disabling my firewall, but still nothing, it spits out an error every time it closes which includes the java error "EXCEPTION_ACCESS_VIOLATION"
[hs_err_pid6416.log](https://github.com/rsbmatt/OSBuddy/files/1411792/hs_err_pid6416.log) (the error)

**Comment by rsbfox** [comment]
Please include the client error log in the osbuddy logs folder and some PC specs. CPU, GPU, OS.

**Comment by rsbfox** [comment]
Moved to discord but I'll post solution here if found.

**Comment by rsbfox** [comment]
2nd gen intel gpu on windows 10. #83 was the fix.
