### ISSUE TITLE
Diary Progress - Excessive CPU usage

### ISSUE THREAD

**Issue by cernodile** [rsbmatt/OSBuddy#309]
Hello,

I am a owner of a **Intel(R) Celeron(R) CPU G530** on 2.40GHz, opening achievement tab while Diary Progress plugin is open spikes the CPU usage A LOT. It makes the game run on 5-15fps instead of 50fps, additionaly I'm using OpenGL, if that's any help.

If I turn the plugin off, the lag spike goes away, when I re-enable it, it comes back.
This is really important for people with such weak CPUs as I have, maybe even weaker ones.

OS: Windows 10 Pro x64, v1709
Memory: 8GB DDR3 1067 MHz (4/4 slot)
GPU: ASUS GeForce 210 (1GB, named "210-1GD3-L")

**Comment by ghost** [comment]
I don't notice any increase in CPU usage when using OpenGL or not and going to the achievement diary. However, When I am not using OpenGL, I can consistently get the FPS to drop from a consistant 50 FPS to 42-43 FPS and it will sit there until I close the achievement diary frame or disable the diary progress option. The achievement diary frame tab is the only tab that has a noticeable affect on FPS.

CPU: Intel i5 4670k 3.40GHz

**Comment by cernodile** [comment]
@Domceru You don't get as big CPU usage increase due to having 4 cores and quite good frequency. However, people with dual-core CPUs and decent frequency suffer from this. Though FPS drop proves there's something clearly wrong with the implementation, possibly a constant string replacing loop.
