### ISSUE TITLE
NPC Tagging with always-right click bug

### ISSUE THREAD

**Issue by Tekonaz** [rsbmatt/OSBuddy#316]
Bug in beta 3.0.24.2 where if you right click a npc and a player is stood at same square(so you get both player options such as trade and npc options), the client crashes and you have to re-open the client. No matter if you have allow tagging of non-attackable NPCs enabled or not.

![2017-11-06_00-54-37](https://user-images.githubusercontent.com/33176182/32420630-7bf13aba-c28d-11e7-9870-831b0c550e12.gif)
![2017-11-06_00-53-29](https://user-images.githubusercontent.com/33176182/32420634-8ca7741e-c28d-11e7-9066-ab703d64c518.gif)

**It only crashes if you have hide/always right-click NPC attack options**

**Comment by Tekonaz** [comment]
![bug](https://user-images.githubusercontent.com/33176182/32420565-66090fda-c28c-11e7-9ad5-6beec907e228.gif)

**Comment by rsbfox** [comment]
Issue unconfirmed for 11 days and in an old beta version. Please reply if this bug is in current live build.

**Comment by rsbfox** [comment]
OK. You opened new issue instead.
