### ISSUE TITLE
Experience Drop: Orb Progress percentage bar missing.

### ISSUE THREAD

**Issue by jannicklorenzen** [rsbmatt/OSBuddy#318]
After the merge of official experience drops and the OSBuddy plugin, the percentage progress bar in the Experience Orbs is gone.

![image](https://user-images.githubusercontent.com/30437792/32624201-d04e110c-c588-11e7-9ab9-6e2e54045f5a.png)

OSBuddy v3.0.24

**Comment by rsbfox** [comment]
Fixed in OSBuddy v3.29.10
