### ISSUE TITLE
Runecrafting: Pouch Overlay 100% opaque

### ISSUE THREAD

**Issue by jannicklorenzen** [rsbmatt/OSBuddy#319]
The update to runecrafting pouches made the overlays 100% opaque, causing you to be unable to see what pouch it is.

![Gifv](https://i.imgur.com/XqktpH5.gif)

OSBuddy v3.0.25

**Comment by UhWatchMe** [comment]
![pic](https://i.imgur.com/Ld8F3cA.png)

My large pouch is broken, now showing another color.

**Comment by eduardocopat** [comment]
Same here, can confirm:

![image](https://user-images.githubusercontent.com/2248490/32689950-5cadbff6-c6d5-11e7-9d6c-7b64fce5767a.png)

**Comment by eduardocopat** [comment]
Seems to be working again now

**Comment by 0tna** [comment]
Fixed.
