### ISSUE TITLE
Cursor Selector: Flickering when using OpenGL

### ISSUE THREAD

**Issue by Nick2bad4u** [rsbmatt/OSBuddy#321]
I normally use the smaller custom cursor in OSB.

When using OpenGL this happens.

<a href="https://gyazo.com/09b81e77d19b5a8f7f12ee6a1d67ee9d"><img src="https://i.gyazo.com/09b81e77d19b5a8f7f12ee6a1d67ee9d.gif" alt="https://gyazo.com/09b81e77d19b5a8f7f12ee6a1d67ee9d" width="336"/></a>

**Comment by rsbfox** [comment]
As far as I know, this is just a problem with how that plugin was written before opengl mode. It might need rewritten and could be broken till opengl is out of beta.

I could be wrong and this is just something easy that just hasn't been looked at yet.

**Comment by rsbfox** [comment]
#98
