### ISSUE TITLE
Issue with Placeholders and Charged Jewelry 

### ISSUE THREAD

**Issue by Unit12p** [rsbmatt/OSBuddy#332]
I'll preface this by saying that I'm not sure if this is an OSB bug or simply an issue with the placeholder system in the game, but something is screwy here.

When removing a charged piece of jewelry that is below it's maximum charge, it is given a placeholder as if it is a piece of jewelry that has one charge on it:
![placeholder1](https://user-images.githubusercontent.com/33982025/33230922-e9993760-d1b1-11e7-97a1-4c8c3955256e.gif)

If the number of charges on the jewelry changes, it is still assigned to the same placeholder of the single charged piece:
![placeholder2](https://user-images.githubusercontent.com/33982025/33230927-0bbc8b94-d1b2-11e7-8668-16b7eb28048d.gif)
![placeholder3](https://user-images.githubusercontent.com/33982025/33230931-17310338-d1b2-11e7-8f4e-1e5636c4bb6d.gif)

This also doesn't allow multiple pieces of the same jewelry with different amounts of charges to have their own placeholders unless it is full, has one charge, or is uncharged. For example, if the only Slayer Ring(7) is taken out of my bank, it is assigned a Slayer Ring(1) placeholder. While that (1) placeholder exists, if another Slayer Ring that is the only of it's charge count is removed, the second is not assigned a placeholder at all.
![placeholder4](https://user-images.githubusercontent.com/33982025/33230995-26e61ac4-d1b3-11e7-82bd-311101fc0862.gif)

Again, I'm not sure whos bug this is, and if it's not OSB's issue I'll be sending this same bug report to Jagex instead.

**Comment by rsbfox** [comment]
This is how Jagex does jewelry place holders.
