### ISSUE TITLE
External Links in Poll Booths

### ISSUE THREAD

**Issue by notraidel** [rsbmatt/OSBuddy#335]
Clicking external links in poll booths will not open them in a browser on Linux using Java 8. 
![bug](https://user-images.githubusercontent.com/19423038/33471193-18e677a8-d63a-11e7-9a09-7c91b512b92c.png)

Getting the following errors when I attempt to open the links:
```
$ java -Dnofork=true -jar games/rs/OSBuddy.jar -vvv
...
...
Error: fk.r hc.e b.w dv.a client.ev client.aq be.p be.run Thread:748 | java.lang.NullPointerException | 0 3113

$ java -version
openjdk version "1.8.0_144"
OpenJDK Runtime Environment (build 1.8.0_144-b01)
OpenJDK 64-Bit Server VM (build 25.144-b01, mixed mode)
```
```
$ java -Dnofork=true -jar games/rs/OSBuddy.jar -vvv
...
...
Error: fk.r hc.e b.w dv.a client.ev client.aq be.p be.run Thread:745 | java.lang.NullPointerException | 0 3113

$ java -version
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
```

**Comment by rsbfox** [comment]
Game in built for openjdk 6 on windows. This bug is in Jagex code but is outside of what is supported. 

Running the client on Linux is not standard and will not always function fully with the large combination of Java and desktop environments.

IMO osbuddy is the easiest way to run osrs on Linux and Matthew uses arch. So I'm gonna leave this open and he might know a fix or be able to add a workaround.

**Comment by rsbmatt** [comment]
@utsukami does your distro have `xdg-open` ?

**Comment by notraidel** [comment]
@rsbmatt Yeah. Here's this if it helps:
```
$ uname -r          
4.14.5-1-ARCH

$ xdg-open --version
xdg-open 1.1.2
```

**Comment by rsbmatt** [comment]
Cool, <3 Arch.

Alright, I'll add a patch into their code to use xdg-open for linux. Should work. I'll let you know when it goes live.

**Comment by rsbmatt** [comment]
@utsukami I went ahead and pushed a change to the `beta` version of the client to make sure it works.

Can you run the client with:

```java -Dnofork=true -Dbranch=OS-matt-development -jar games/rs/OSBuddy.jar -vv``` 

... and let me know how it goes (version should be 3.0.26.5)? I'm in the discord if you'd rather chat in there.

**Comment by notraidel** [comment]
@rsbmatt Can confirm it's working as intended on the beta client `v3.0.26.5`
