### ISSUE TITLE
plugin: Food overlay. add extra food items

### ISSUE THREAD

**Issue by 0tna** [rsbmatt/OSBuddy#339]
a few food items Shaun#1680 suggested.
[![Screenshot from Gyazo](https://gyazo.com/3cb7e57cf79d26ea1c4b487c48cdf8c5/raw)](https://gyazo.com/3cb7e57cf79d26ea1c4b487c48cdf8c5)

**Comment by ShaunDreclin** [comment]
tea is "Cup of tea" in game btw, and wine is "Jug of wine"

also the ttl and choc bomb heal 15, http://oldschoolrunescape.wikia.com/wiki/Template:Gnome_cooking for reference

**Comment by ShaunDreclin** [comment]
woot 🎉
