### ISSUE TITLE
Grand Exchange History is not tracking

### ISSUE THREAD

**Issue by gtjamesa** [rsbmatt/OSBuddy#344]
If I login to rsbuddy.com/exchange/history, my last entries were 28th September. I have posted this into Discord previously, but have not yet seen a related ticket.

https://i.imgur.com/ekesMyh.png

**Comment by Fudster** [comment]
I would love to see this fixed. This tool feature is useful :)

**Comment by sadousky14** [comment]
I really miss having the ability to view how much money I've made flipping. I'd be grateful if you guys were able to get the exchange history back online!

**Comment by Chrislorious** [comment]
Would love to see this feature back up and running so I can keep track of all my flips.

**Comment by provenkaedon** [comment]
I would love if this feature was fixed it is very helpful to my overall experience

**Comment by ActuallyTrent** [comment]
I would be really excited about this feature being fixed.

**Comment by gabessdsp** [comment]
Any updates on the fix for this? I just realized it's not tracking and it really stinks :/

**Comment by SavageVibes** [comment]
Any updates?

**Comment by rsbfox** [comment]
This is waiting on the website being migrated to a new host. The data is still being tracked. When it's fixed you should be able to see the trades not shown before.

**Comment by MattGarnettWelsh** [comment]
Any ETA on this one @rsbfox?

**Comment by rsbfox** [comment]
Full server migration to the google cloud should be finished within the next week.

There are some other big jobs being done as well. I'll ask the website guy if the exchange and clue pages can be fixed soon.

**Comment by YusufHabib** [comment]
is it still be worked on?

**Comment by rsbfox** [comment]
History should already be fixed.

**Comment by YusufHabib** [comment]
There's no history of transactions

**Comment by rsbfox** [comment]
Can you post a screenshot?

I see recent trades from my account. I did notice an issue loading older history though.

**Comment by YusufHabib** [comment]
________________________________

**Comment by FixGETrackerPLS** [comment]
Any updates? Still not working according to GE Tracker

**Comment by Visco33** [comment]
hopefully there's an update soon, really great feature

**Comment by maptap123** [comment]
Can you please fix this I will switch from runelite to osbuddy if you allow me to sync with ge-tracker

**Comment by sp3sh** [comment]
History still seems to be an issue, is this going to be fixed?

**Comment by ChocolaKuma** [comment]
can this get fixed?

**Comment by ymebrugts** [comment]
This is still not fixed? I guess it's not possible anymore.
