### ISSUE TITLE
Coin drop value not multiplied by quantity

### ISSUE THREAD

**Issue by cmg5461** [rsbmatt/OSBuddy#345]
It seems  for x coins on the ground, value is always 1.

Coins*amount should be highlighted when > item over price threshold.

See:
![osbuddy64_2017-12-13_17-39-50](https://user-images.githubusercontent.com/9099791/33966337-4645b004-e02d-11e7-9b49-3a86841fe6a7.png)
![osbuddy64_2017-12-13_17-40-10](https://user-images.githubusercontent.com/9099791/33966338-4653f4b6-e02d-11e7-9219-279286199a97.png)
![osbuddy64_2017-12-13_17-40-19](https://user-images.githubusercontent.com/9099791/33966339-4662031c-e02d-11e7-8dff-1dbfc2e4a3c0.png)
![osbuddy64_2017-12-13_17-41-38](https://user-images.githubusercontent.com/9099791/33966340-466fb5ac-e02d-11e7-8138-930b2a005a6b.png)

**Comment by rsbmatt** [comment]
Thanks, fixed, ready for release in next version. 
![image](https://user-images.githubusercontent.com/23370763/33968790-d536539a-e037-11e7-9668-6a3981a25069.png)
