### ISSUE TITLE
Option Reorder: Left click harpoon sharks

### ISSUE THREAD

**Issue by rsnjames** [rsbmatt/OSBuddy#35]
Making the left click option harpoon instead of net. 

Locations of where the option would need to be changed are the Fishing Guild, Catherby, Burgh De Rott, Rellekka and Jatizso.

**Comment by rsbfox** [comment]
Please add the locations.

**Comment by rsnjames** [comment]
Sure, the locations are Fishing Guild, Catherby, Burgh De Rott, Rellekka and Jatizso.

**Comment by rsnjames** [comment]
@rsbmatt I've gone ahead and gathered the ID's for the harpoon/net (shark fishing) spots for each location.

I'd like the spot to be made always left click harpoon on these fishing spots. 

Rellekka: Fishing spot #3915 (0) [-1] [Net, null, Harpoon, null, null]

Jatizso: Fishing spot #5821 (0) [-1] [Net, null, Harpoon, null, null]

Catherby: Fishing spot #1520 (0) [-1] [Net, null, Harpoon, null, null]

Fishing Guild: Fishing spot #1511 (0) [-1] [Net, null, Harpoon, null, null]

Burgh De Rott (has two) ID's: Fishing spot #4476 (0) [-1] [Net, null, Harpoon, null, null]
Fishing spot #4477 (0) [-1] [Net, null, Harpoon, null, null]

**Comment by Hannah-GBS** [comment]
Can this get a bump?

**Comment by rsbmatt** [comment]
Done.

Feature is now in Beta if you want to test it. It should be live in v3.2

**Comment by hem-brahmbhatt** [comment]
I'm on v3.2.1 and I'm unable to find the option...

**Comment by rsbfox** [comment]
It's under the HUD plugin settings.

**Comment by hem-brahmbhatt** [comment]
Looks like it only applies to Net/Harpoon spots, and not Cage/Harpoon spots as well. Would be useful for fishing swordies over lobsters with dragon harpoon.

**Comment by rsbfox** [comment]
Yes the title of this issue is left click harpoon sharks.

I agree though. I'll add it as an issue to our internal bug tracker.
