### ISSUE TITLE
Idea: Logging

### ISSUE THREAD

**Issue by iDevelopThings** [rsbmatt/OSBuddy#365]
So I had this idea, I could quite easily code a website to handle all this, along with an API for OSBuddy, but then I noticed it's not open source.

Wouldn't it be cool to be able to see what drops your friends got, how much killcount they have on an npc, what quests they completed, track xp gains etc.

It would be super easy to implement this into OSBuddy, for questing, you take a printscreen, so you just add an API request into that, and so on for kc etc.

If you'd be interested on working with me for the website, I would be happy to do it.

**Comment by UhWatchMe** [comment]
You mean the adventure log from RS3? Would be neat though.

**Comment by iDevelopThings** [comment]
@xNonCombat yeah basically

**Comment by rsbfox** [comment]
Yes. We want to do all this in the future. No ETA just yet!

~rsb_fox

**Comment by iDevelopThings** [comment]
@rsbfox Awesome to hear! If theres any way i can help with the backend let me know :) I have 10+years web dev experience. I work in mainly Laravel+VueJS/NodeJS
