### ISSUE TITLE
Add Super antifire potion: Timer Manager

### ISSUE THREAD

**Issue by 0tna** [rsbmatt/OSBuddy#366]
Title ^ 
Potion id's
21987 : Super antifire potion(1)
21984 : Super antifire potion(2)
21981 : Super antifire potion(3)
21978 : Super antifire potion(4)

**Super antifire potion provides complete immunity to a dragon's breath for _2 minutes_.**

**Comment by rsbmatt** [comment]
@0tna can you get me the exact message as seen from the message debugger?

**Comment by 0tna** [comment]
[flags=105, prefix="null", sender="" message="You drink some of your super antifire potion."]
[flags=105, prefix="null", sender="" message="You have 1 dose of potion left."]
[flags=0, prefix="null", sender="" message="<col=7f007f>Your super antifire potion is about to expire.</col>"]
[flags=0, prefix="null", sender="" message="<col=7f007f>Your super antifire potion has expired.</col>"]
@rsbmatt

**Comment by rsbfox** [comment]
Messages for 3 & 2.

[flags=105, prefix="null", sender="" message="You drink some of your super antifire potion."]
[flags=105, prefix="null", sender="" message="You have 3 doses of potion left."]
[flags=105, prefix="null", sender="" message="You drink some of your super antifire potion."]
[flags=105, prefix="null", sender="" message="You have 2 doses of potion left."]

**Comment by 0tna** [comment]
Super antifires now last 3 minutes per dose, instead of 2.
