### ISSUE TITLE
OSBuddy Loader error

### ISSUE THREAD

**Issue by Nightfirecat** [rsbmatt/OSBuddy#368]
A small window pops up on launch with the following lines present:

```
Error downloading configuration, trying again Server returned HTTP response code: 504 for URL: http://cdn.rsbuddy.com/live/osbuddy.ver?ts=1515712941514
Error downloading configuration with fallback DNS, trying again Server returned HTTP response code: 504 for URL: http://cdn.rsbuddy.com/live/osbuddy.ver?ts=1515712942108
Error downloading configuration altogether Malformed hashes file ()
Unable to find the hash for jar.json
```

This did not block the client from loading&mdash;this pop-up window was in addition to the client window.

**Comment by rsbfox** [comment]
The website is down. The client could not check for updates. Just minimize window. If you still get this error in 24 hours please post on the discord support channel.

Thanks.
