### ISSUE TITLE
Jewelry frame/equipment won't show jewelry with (1) charge

### ISSUE THREAD

**Issue by Jalopyy** [rsbmatt/OSBuddy#370]
Any other charge number shows fine, but the entire number and parentheses disappear when there is only 1 charge left.

**Comment by Jalopyy** [comment]
https://i.imgur.com/GXtUAiK.jpg 2 charges shown in frame/equipment panel
https://i.imgur.com/1TxER0N.jpg No charges shown at 1 charge
https://i.imgur.com/4iUm0A4.jpg 0 charges shown in frame/panel.

**Comment by rsbfox** [comment]
https://github.com/rsbmatt/OSBuddy/issues/131

**Comment by rsbfox** [comment]
Update to say this is actually a limitation in the osrs engine. That plugin uses the client code to draw the items there. Items in osrs cannot have a 1 as a stack size visible.
