### ISSUE TITLE
A few suggestions

### ISSUE THREAD

**Issue by Jalopyy** [rsbmatt/OSBuddy#371]
1) Tracker for how many more times you can fill an essence pouch before it degrades.
2) Option to individually move/resize more frames individually, IE jewelry, target, etc (I hear this is in the works though, pls soon)
3) If it's possible (not familiar with the limitations of 3rd party clients for OSRS), an option to make the teleport option on things like quest cape and jewelry the left click option if you have an essence pouch in your inventory. Would make RCing a bit less annoying. Maybe even to set which teleport, if there are multiple (glories, duel rings, max cape) is the left click.
4) If you shift-click an item in the bank, it automatically withdraws all (again, I don't know limitations)
5) Allow us to change the color of the bar on the progress orbs (currently white by default) to the 'color' of the correlated skill.

**Comment by NonCombat** [comment]
1. Would be nice to see.
2. I think in general all UI should be resizeable so I agree.
3. Definitly should be possible, setting the teleport destination to a left click I don't think Jagex would agree with that. Since you need to Right-Click to see the options. But left-clicking it and then showing the teleport locations, sure.
4. Would be nice, but should not be done from OSB's side. Sure they could manage this with packets, but don't know if Jagex likes that.
5. More like 1, having an option to customize. Agreed.

**Comment by rsbmatt** [comment]
1. The problem with this is that the data for this is not easily accessible by the client (that I know of). What we can do is provide a counter which only works in session, which means if you reload the client it will not remember the previous counters of the pouches.

2. Many of the plugins will be getting added to the current status indicator (or their own), which is a movable and resizable interface. Currently the only plugins that support the indicators are the: 
- [x] Current boosts
- [x] Prayer

3. Swapping the opts of any entity in the game is trivial. It's all a matter of what the defaults _should_ be. Whereas I believe that many of the reorders we have should be made by Jagex at the cache level, we do have the ability to swap them as we please. Ideally I would like to add a system where users can select an entity in game, and set what they want the left click option to be. For now we simply add toggles to individual entities based on what the majority of our community seems to think the left-click opt should be.

4. This is easily implemented. I'll look to add it as a toggle to either the `Bank` plugin, or the `Configure shift click` plugin.

5. Already on my list.

**Comment by Jalopyy** [comment]
I assumed that was the case for 1), which is fine. Personally, when I finish RCing for the day/session, the last run I do is always through the abyss (since lately I've been doing cosmics via quest cape) so pouches are fresh for the next time. It'd just be nice so there's less guesswork about when something is gonna degrade, since I keep track of it based on how many runes I have in my inven compared to how many I do a run.

And for 4), the latter sounds better. Being able to shift-click withdraw-X or withdraw-all separately would be great for things like fletching/herb where you want to withdraw 14 most of the time.

**Comment by NonCombat** [comment]
@rsbmatt The small pouch I don't know, not on the wiki (Pretty sure it does not degrade though). However the medium pouch after its 44th use. The Large after the 31th use and 40th use. Giant after the 12th time. You could store those variables in the json of settings?

http://oldschoolrunescape.wikia.com/wiki/Small_pouch
http://oldschoolrunescape.wikia.com/wiki/Medium_pouch
http://oldschoolrunescape.wikia.com/wiki/Large_pouch
http://oldschoolrunescape.wikia.com/wiki/Giant_pouch
