### ISSUE TITLE
Dead click on run data orb in fixed mode

### ISSUE THREAD

**Issue by rsbfox** [rsbmatt/OSBuddy#376]
Near the top.
https://gyazo.com/2434edf80a16b40bfe83cf52eb96e55e

Doesn't happen with official client.
v3.0.28

**Comment by rsbmatt** [comment]
![image](https://user-images.githubusercontent.com/23370763/36747772-e4c90a74-1bc3-11e8-8a15-2db3ef6879c6.png)

Above is the clickbox as defined by Jagex. testing by placing mouse inside the bounds in fixed mode will register as a click and run will toggle.
