### ISSUE TITLE
Digsite pendant is off by 1 teleport

### ISSUE THREAD

**Issue by MalakaJones** [rsbmatt/OSBuddy#378]
Jewellery plugin is off by 1 teleport for the Digsite pendant. 

![digsite_pendant_1](https://user-images.githubusercontent.com/15826583/35307949-4768ab88-0073-11e8-98dc-555469007046.png)
![digsite_pendant_2](https://user-images.githubusercontent.com/15826583/35307950-477ac28c-0073-11e8-9192-81d7217be9ff.png)

**Comment by rsbfox** [comment]
https://github.com/rsbmatt/OSBuddy/issues/131
