### ISSUE TITLE
OpenGL: Hitbox issue with elevated areas

### ISSUE THREAD

**Issue by jannicklorenzen** [rsbmatt/OSBuddy#38]
Unable to move around by clicking the ground in certain elevated areas. This includes any boat when below deck, Taverley dungeon slayer exclusive area, Asgarnian dungeon wyvern slayer exclusive area and in some instances docks as seen below.
https://fat.gfycat.com/UntimelyUnlinedDeermouse.webm

**Comment by rsbfox** [comment]
See [#21](https://github.com/rsbmatt/OSBuddy/issues/21)
