### ISSUE TITLE
The roof of the wall surrounding the GE does not render using OpenGL w/ roof-removal enabled

### ISSUE THREAD

**Issue by Meegul** [rsbmatt/OSBuddy#384]
Title explains the issue. This appears to affect all platforms.
OpenGL enabled:
![no_roof_opengl](https://user-images.githubusercontent.com/4149093/35478728-2ed181d8-03b3-11e8-9cda-18646cbf2432.PNG)

OpenGL disabled:
![no_roof_standard](https://user-images.githubusercontent.com/4149093/35478735-3f729248-03b3-11e8-92cd-946bc8b35525.PNG)

**Comment by Hannah-GBS** [comment]
Seconding this, has been a long-running issue. Over a year old, at least.

**Comment by 0tna** [comment]
Fixed on V3.21 (beta) https://i.imgur.com/Btvg3HJ.jpg
