### ISSUE TITLE
Runecrafting: Mage of Zamorak still not displaying

### ISSUE THREAD

**Issue by Furutze** [rsbmatt/OSBuddy#39]
![wtdscga](https://user-images.githubusercontent.com/30447185/28592372-6d0d6ec6-7191-11e7-9d22-9796389de16c.png)
![f9xvp2u](https://user-images.githubusercontent.com/30447185/28592088-a50dbe26-7190-11e7-8691-53800cf73e73.png)
![ongzhrd](https://user-images.githubusercontent.com/30447185/28592169-d0ff1bc4-7190-11e7-9b73-84a7bf5f7e26.png)

![](http://i.imgur.com/IBSNcd9.png)

Am I doing something wrong??

**Comment by rsbfox** [comment]
No. See [#7](https://github.com/rsbmatt/OSBuddy/issues/7)
