### ISSUE TITLE
'right click > lookup' in chat

### ISSUE THREAD

**Issue by H1Tom** [rsbmatt/OSBuddy#395]
Right click > Hiscore option is not working in chat, pm's & friends chat. 
![image](https://user-images.githubusercontent.com/35881266/35773551-a2d4e7cc-0990-11e8-88a8-8e8ec07e3253.png)
![image](https://user-images.githubusercontent.com/35881266/35773555-bb3535ba-0990-11e8-9ed5-f25d9fa9823d.png)
![image](https://user-images.githubusercontent.com/35881266/35773561-c3e2de38-0990-11e8-93fe-31d8097666f1.png)

**Comment by Nick2bad4u** [comment]
I noticed this too. If you have them in your CC and you have permission to kick. The look-up disappears. Same thing happens if you right click someone you're not friends with. Add Friend Ignore Friend appear instead of Look-up

**Comment by rsbmatt** [comment]
- [x] Fixed lookup in chat (Interface index had changed).
- [x] Added the ability to add more options than 5 to the context menu for chat messages (to account for @Nick2bad4u's message)
