### ISSUE TITLE
Dagannoth rex not showing up in loottracker

### ISSUE THREAD

**Issue by Onurrr** [rsbmatt/OSBuddy#398]
^^

**Comment by Onurrr** [comment]
@pacmanfox what info would you need

**Comment by rsbfox** [comment]
Need to know if it happens to everyone, why is it bugged and how does loot tracker work? Not asking you for more info. Just stating that this issue is vague.

It's possible this bug is unrelated to Rex itself. It could be impacting multiple monsters at once. I'll poke people about this issue.

**Comment by rsbfox** [comment]
#184
