### ISSUE TITLE
Achievement diaries plugin

### ISSUE THREAD

**Issue by Onurrr** [rsbmatt/OSBuddy#400]
Show's I've completed Karamja mid while I haven't:

![image](https://user-images.githubusercontent.com/9193729/35909259-4af81db6-0bf3-11e8-977b-98c8b0866227.png)

![image](https://user-images.githubusercontent.com/9193729/35909265-50d861e6-0bf3-11e8-97b7-3b38fa7ebfb3.png)

**Comment by MalakaJones** [comment]
Got the same glitch while doing karam diary

**Comment by rsbmatt** [comment]
Pretty sure  I have a fix for this now... will push.
