### ISSUE TITLE
FarmingTracker glitch with Falador herb patch

### ISSUE THREAD

**Issue by MalakaJones** [rsbmatt/OSBuddy#401]
The FarmingTracker does not seem to be able to pick up the amount of herbs you harvest on Falador patch only. This leads to erronous profit calculations. I'm not sure if this is related to the fact that I have completed Falador hard diary and that the exp I get from those herbs is not the usual one.

**Comment by rsbfox** [comment]
This plugin needs a rewrite in the future. The developer who made it isn't working at rsbuddy anymore.
