### ISSUE TITLE
Fix armadyl spawn timer bug

### ISSUE THREAD

**Issue by rsbfox** [rsbmatt/OSBuddy#411]
> if you are chinning the minion when arma dies, the boss spawn timer will not appear. If you are attacking arma directly it will.
Bug has been reported since 2016? :(

No timer:
https://cdn.discordapp.com/attachments/268464847006597122/417356837449367572/06c543fa814bdeda3ac885e3b460c26f.mp4

Timer:
https://cdn.discordapp.com/attachments/268464847006597122/417356852146470932/044a2eb76a9370e8efb5f4ac9cb597b6.mp4
v3.1.1

**Comment by pacmanfox** [comment]
@rsbmatt Is this bug easy to fix or will it require a lot of work?
