### ISSUE TITLE
Calculator Error + Request

### ISSUE THREAD

**Issue by Jalopyy** [rsbmatt/OSBuddy#416]
1) Cooking karambwan (thoroughly) gives 190xp. The listed 80xp is for a poison karambwan, which the average person probably isn't going to do in bulk. Would be nice to either make the listed amount 190xp, or have two separate listings for both thorough and poisoned.

2) Add Teak Magic Wardrobes to the Construction calculator.

**Comment by Jalopyy** [comment]
E: Nvm the suggestion I was gonna add here was already implemented.

**Comment by rsbfox** [comment]
Its been added to our internal issue tracker! Please keep an eye on https://rsbuddy.com/osbuddy/patch_notes or the #announcements channel of https://discord.gg/osbuddy for news of when this has been fixed. Thank you for taking your time to make OSBuddy better for everyone!
