### ISSUE TITLE
Jewel teleport addon overwrites inventory items

### ISSUE THREAD

**Issue by MalakaJones** [rsbmatt/OSBuddy#418]
Since a couple days, I realised that the jewel addon sometimes does not reset when you bank your jewels. You then end up with your inventory items amounts being overwritten (only at the same place the jewel was previously).

Logging in-out solves the issue.
![jewel_addon](https://user-images.githubusercontent.com/15826583/37067872-dd2ce0cc-2179-11e8-9571-9f41c3d73cc0.PNG)
![inventory_jewel_addon](https://user-images.githubusercontent.com/15826583/37067878-e11a20b4-2179-11e8-946d-3fc55b32bfa7.PNG)

**Comment by rsbfox** [comment]
This is being tracked and worked on internally thanks. OSB-49
