### ISSUE TITLE
Add customizable precision to bank value decimal places

### ISSUE THREAD

**Issue by cmg5461** [rsbmatt/OSBuddy#420]
https://i.imgur.com/Vjwabh2.png

Other clients have up to 1GP precision. After 1B, precision goes to 2 digits or 100M, which is not helpful.

This option could be in the bank overlay plugin with selectable gp, K, M or B. K, M and B can have user definable decimal precision.

**Comment by rsbfox** [comment]
There is a toggle to show exact value now. I'm sure Matthew will consider the rest when he finishes bank plugin rework. The actual problem with not being able to see enough is fixed so I'll closing this one.
