### ISSUE TITLE
Shazam! doesn't work in Friends Chats

### ISSUE THREAD

**Issue by GameDevRogie** [rsbmatt/OSBuddy#434]
Noticed recently as I've been streaming that it doesn't work in Friends chats - Presumably the rank images before names has broken it because I swear that It used to - It seems to work in PM just fine.

If it could work in FC's it would be super useful as it's an easy way I can give people a day of pro without much effort to interact with my stream viewers/community.

Also if possible could I get 'Skiller' added to the Shazam list please?

Cheers!

**Comment by rsbfox** [comment]
Add RSB Fox also. :)

**Comment by rsbfox** [comment]
It works in friends chats for me.
