### ISSUE TITLE
Clue Scroll : Text not appearing correctly.

### ISSUE THREAD

**Issue by UhWatchMe** [rsbmatt/OSBuddy#44]
![Image of the text of the clue](http://i.imgur.com/nK6iOXQ.png)

**Comment by jannicklorenzen** [comment]
![image](https://user-images.githubusercontent.com/30437792/29484936-7203cb6e-84c9-11e7-8368-ea13f7e820ac.png)


OSBuddy v3.0.19

**Comment by jannicklorenzen** [comment]
The issue here is due to special characters used on the Wikia.

![image](https://user-images.githubusercontent.com/30437792/29484968-f8d738d8-84c9-11e7-8288-2eadb49ef2fc.png)
