### ISSUE TITLE
Force left click (Pro Plugins) without having to use Shift click

### ISSUE THREAD

**Issue by permedd** [rsbmatt/OSBuddy#443]
Are you able to make it so we don’t have to shift left click and we can just do left click?
i don't want to change my windows settings can you do it on the client maybe?

this will bring a lot pkers to use the client i think it is worth adding? or maybe just do it for safe zone because it is an overpowered plugins to use at the wilderness? your choice :)

**Comment by rsbfox** [comment]
Sorry. Modifying shift click is in line with how the game limits it. Just letting players change options always might upset Jagex.
