### ISSUE TITLE
Master scroll book (empty) is not searchable in Exchange

### ISSUE THREAD

**Issue by HalalSnakbar** [rsbmatt/OSBuddy#46]
The item exists in the database ([https://rsbuddy.com/exchange?id=21387&](https://rsbuddy.com/exchange?id=21387&)), but it cannot be searched for.

**Comment by rsbfox** [comment]
![21387](https://user-images.githubusercontent.com/30416150/28630483-59c2a266-71f8-11e7-84c1-4f766dc91cac.png)
Image for exchange.
