### ISSUE TITLE
Hiscores: Add lookup option to names in chat

### ISSUE THREAD

**Issue by rsbfox** [rsbmatt/OSBuddy#52]
- [ ] In chatbox.
- [ ] in clan chat list.

**Comment by softwarez** [comment]
Also in friends chat and friends list would be nice.

**Comment by jannicklorenzen** [comment]
"offers autocomplete based on who is around you, on your friends list, or in your friends chat"
![image](https://user-images.githubusercontent.com/30437792/29305220-c7490a92-8197-11e7-9785-3e9278a4aa1d.png)

Does not work with people around you and those in friends chat.

OSBuddy v3.0.18
