### ISSUE TITLE
Experience Tracker: Missing arrow indicating it's clickable

### ISSUE THREAD

**Issue by jannicklorenzen** [rsbmatt/OSBuddy#54]
Needs an arrow to show people it's actually clickable and expandable. I only discovered it by complete accident.

![image](https://user-images.githubusercontent.com/30437792/28666263-f2c165a0-72c6-11e7-973a-85f27327eabc.png)

Currently the arrow is only visible when it's already expanded.
![image](https://user-images.githubusercontent.com/30437792/28666277-00c141ac-72c7-11e7-8ec5-c0036dc38bd3.png)

Current arrow is also reversed.
v3.0.12

**Comment by rsbfox** [comment]
Addition: Mentioned arrow is reversed and added client version for you.
