### ISSUE TITLE
Hunter: Trap overlay shown on Lletya bank booths

### ISSUE THREAD

**Issue by jannicklorenzen** [rsbmatt/OSBuddy#55]
The trap overlay from the hunter plugin will incorrectly show the bank booths in Lletya as traps.

https://gfycat.com/IlliterateFamiliarFattaileddunnart

OSBuddy v3.0.12

**Comment by rsbmatt** [comment]
Was just a typo in the loc id. 

Fixed in beta, pull request made into the live client.
