### ISSUE TITLE
Status Indicators: Cannot be resized or moved in OpenGL

### ISSUE THREAD

**Issue by HalalSnakbar** [rsbmatt/OSBuddy#59]
Turning off OpenGL fixes the issue. OSBuddy version 3.0.12, Java 9

**Comment by jannicklorenzen** [comment]
I have no problem doing so in OpenGL mode. 

https://gfycat.com/PoorTangibleAlaskankleekai

OSBuddy v3.0.12

**Comment by HalalSnakbar** [comment]
https://streamable.com/nfqv4

After further testing, the bug seems to be limited to java 9.

**Comment by rsbmatt** [comment]
Thanks for the heads up. We're currently redoing a huge portion of OpenGL, including changing the library we use (LWJGL2). Hopefully, with these changes it will remedy this issue, if not, I'll see what I can do.

**Comment by rsbfox** [comment]
Not happening for me on Java 10.
