### ISSUE TITLE
Blast furnace only gives an xp drop every other inventory

### ISSUE THREAD

**Issue by Joord** [rsbmatt/OSBuddy#61]

**Comment by Joord** [comment]
Noizex - Today at 7:35 PM
@Jord I believe it's due to packet loss/server lag - I only noticed it when DDOS attacks where happening, and Rousey is experiencing it in a very heavily packed area where lag is bound to happen

**Comment by jannicklorenzen** [comment]
After some testing I can confidently say it's  a problem unique to world 52. 3 people have reported they got this bug when in world 52, myself included.
It appears to be a "worldwide" issue, and not only for the Blast Furnace area.

Not sure if Jagex bug or if german worlds are having issues (and it being a Blast Furnace world where a lot of people are packed into 1 place).

https://gfycat.com/WeightyBasicDunnart

https://gfycat.com/VigorousDismalEquestrian
