### ISSUE TITLE
Woodcutting: System notifications are not triggered for birdnest drops

### ISSUE THREAD

**Issue by philtyl** [rsbmatt/OSBuddy#68]
Version: v3.0.12
Observed Location: Magic trees in woodcutting guild; Yew trees in woodcutting guild

Birdnest drops are no longer triggering system notifications or highlighting the tile of the dropped nest.

![screenshot at 2017-07-28 06-15-45](https://user-images.githubusercontent.com/1184136/28713465-bb507c3a-7354-11e7-8084-1328664a34e4.png)

![screenshot at 2017-07-28 06-25-20](https://user-images.githubusercontent.com/1184136/28713576-3723d6ae-7355-11e7-9959-f63f5e94214d.png)

**Comment by rsbfox** [comment]
@rsnjames bug-unconfirmed till you reproduce it. Then you switch to one of the other bug labels. Thanks. Thanks for using issue tracker Deprecated.

**Comment by rsbfox** [comment]
Confirmed.

All unexchangeable nest ids. Not sure all of them are dropped while woodcutting.
5070, 5071, 5072, 5073, 5074, 7413, 13653, 19712, 19714, 19716, 19718
Message
[flags=0, prefix="null", sender="" message="<col=ff0000>A bird's nest falls out of the tree.</col>"]

**Comment by rsbmatt** [comment]
Fixed in beta, v 3.0.14.5
