### ISSUE TITLE
Runecrafting: Highlight areas, shortcuts and overlay bugs

### ISSUE THREAD

**Issue by rsnjames** [rsbmatt/OSBuddy#7]
- [ ] Clickable area is no longer highlighted.
- [x] Zamorak mage overlay
- [ ] Shortcut markers, some are missing or wrong.
This one is showing agility icon on minimap.
![image](https://user-images.githubusercontent.com/30416150/28743338-6fdfef1c-7415-11e7-97d8-dad65e4efcf4.png)
Missing woodcut icon
![image](https://user-images.githubusercontent.com/30416150/28743340-9644d2a8-7415-11e7-99bc-a88c7f7e2893.png)
This one isn't any skill. Just instant entrance. Could mark agility or find another icon.
![image](https://user-images.githubusercontent.com/30416150/28743354-d6ce9a52-7415-11e7-9000-33a0b7528113.png)
- [x] Rock shortcut triggered by any object named rock? Could do area check for abyss.
![image](https://user-images.githubusercontent.com/30416150/28776371-5f31ef20-75c4-11e7-8a3a-a158aa1f8882.png)
![image](https://user-images.githubusercontent.com/30416150/28776391-7833f446-75c4-11e7-9d51-324ab13bc853.png)
- [x] Shift-click empty pouches setting isn't needed and does nothing

v3.0.10

**Comment by rsbfox** [comment]
All rifts or just some of them? And what version is your client?

**Comment by rsnjames** [comment]
It appears that the clickable area isn't highlighted unless the same rune is displayed.

E.G. "Display Cosmic rune" must be enabled in plugin settings in order for the mark clickable area of abyssal rift to work for the cosmic rune.  

I'm not sure if that's by design, but imo you should be able to have the clickable area highlighted without needing to have the rift itself be displayed (you don't need the minimap icon if you have the highlighted clickable area on your screen).

The zamorak mage overlay also broke shortly after I changed what area of the rift was marked.  I'm not sure if that's related or if it just randomly stopped working. 

OSB version is 3.0.10.

**Comment by rsbfox** [comment]
Zamorak mage overlay fixed in beta

**Comment by rsbfox** [comment]
Zamorak mage overlay fixed

**Comment by rsbfox** [comment]
Zamorak mage overlay bugged

**Comment by rsbfox** [comment]
@rsbmatt Bug wasn't fixed fully by update.

**Comment by rsbfox** [comment]
![image](https://user-images.githubusercontent.com/30416150/28616162-b0a4ce12-71c9-11e7-9334-c6dc540c6956.png)

Seems to be issue with shortcut markers too.

**Comment by UhWatchMe** [comment]
I encountered this little profit with "Show total amounts" and "Show profit" 

![Image of overlay](http://i.imgur.com/SmbOBd8.png)
![Image of settings](http://i.imgur.com/rU1UuBF.png)

I turned it off, but they do still appear while toggled off.

Here it seems to give the Agility instead of Firemaking

![Image of incorrect icon](http://i.imgur.com/hxz6ex1.png)

Chop Tendrils the woodcutting one never appears 

![Image of Chop Tendrils not shwoing](http://i.imgur.com/7AxgrG6.png)

**Comment by rsbfox** [comment]
Will investigate and add to main post. Thanks.

**Comment by Furutze** [comment]
I have found what triggers that profit thing that xNonCombat mentioned it's the mining plugin.

@pacmanfox

**Comment by rsbfox** [comment]
@Furutze I noticed James split that off into another issue. Normally I'd merge it all into runecrafting bugs. But staff have already given it a priority label. So removing that from here. See #25

**Comment by rsbfox** [comment]
Zamorak mage fixed. https://rsbuddy.com/osbuddy/patch_notes/3.0.25
