### ISSUE TITLE
Jewelry: New items

### ISSUE THREAD

**Issue by rsbfox** [rsbmatt/OSBuddy#76]
- New wearable teleports
- [ ] Pharaoh's sceptre
> Pharaoh's sceptre (8)#13074
> Pharaoh's sceptre (7)#13075
> Pharaoh's sceptre (6)#13076
> Pharaoh's sceptre (5)#13077
> Pharaoh's sceptre (4)#13078
> Pharaoh's sceptre (3)#9044
> Pharaoh's sceptre (2)#9046
> Pharaoh's sceptre (1)#9048
> Pharaoh's sceptre#9050
- [ ] Enchanted lyre
> Enchanted lyre(5)#13079
> Enchanted lyre(4)#6127
> Enchanted lyre(3)#6126
> Enchanted lyre(2)#6125
> Enchanted lyre(1)#3691
> Lyre#3689
- [ ] Slayer ring
> Slayer ring (8)#11866
> Slayer ring (7)#11867
> Slayer ring (6)#11868
> Slayer ring (5)#11869
> Slayer ring (4)#11870
> Slayer ring (3)#11871
> Slayer ring (2)#11872
> Slayer ring (1)#11873
- [ ] Necklace of passage
> Necklace of passage(5)#21146
> Necklace of passage(4)#21149
> Necklace of passage(3)#21151
> Necklace of passage(2)#21153
> Necklace of passage(1)#21155
- [ ] Ring of returning
> Ring of returning(5)#21129
> Ring of returning(5)#21132
> Ring of returning(5)#21134
> Ring of returning(5)#21136
> Ring of returning(5)#21138
- [ ] Burning amulet
> Burning amulet(5)#21166
> Burning amulet(4)#21169
> Burning amulet(3)#21171
> Burning amulet(2)#21173
> Burning amulet(1)#21175
- Equipable non-tele like abyss bracelet
- [ ] Castle wars bracelet
> Castle wars bracelet(3)#11079
> Castle wars bracelet(2)#11081
> Castle wars bracelet(1)#11083
- New inventory only teleport
- [ ] Teleport crystal
> Teleport crystal (5)#13102
> Teleport crystal (4)#6099
> Teleport crystal (3)#6100
> Teleport crystal (2)#6101
> Teleport crystal (1)#6102
> Tiny elf crystal#6103

**Comment by rsnjames** [comment]
The Dodgy Necklace & Binding Necklace need to be added to the status indicator. Currently, neither show the remaining charges.

**Comment by rsbfox** [comment]
Moved to OSB-298
