### ISSUE TITLE
Fps drops when moving mouse

### ISSUE THREAD

**Issue by rsbfox** [rsbmatt/OSBuddy#78]
Posting for Wemb#4816 on discord. Please message him for questions or updates.
-
![_3415d696d689bcb71680ffbffbf9d747-gif](https://user-images.githubusercontent.com/30416150/28732779-40da942e-73a7-11e7-8718-e53046103363.gif)
> OSBuddy version: 3.0.13
> Operating system: Mac OS X
> Architecture: x86_64
> Java version: 1.8.0_20-ea
> Total CPU threads: 8
> Max memory: 1037959168
> Free memory: 236043064
> Total memory: 451174400
![image](https://user-images.githubusercontent.com/30416150/28732850-81b6d8ea-73a7-11e7-9f06-78a289fef267.png)

Steps taken to try and resolve this.

1. Installed new copy of application.
2. Cleared osbuddy files.
```
 rm -rf ~/.osbuddy/
 rm -rf ~/jagexcache/
```
Other information: Been happening for a few months. Only happens on rsbuddy, not konduit or runeloader. Couldn't reproduce on same operating system.

**Comment by rsbfox** [comment]
Second case of this. https://www.reddit.com/r/2007scape/comments/6q6srs/how_can_i_boost_my_osbuddy_performance_on_my/
![image](https://user-images.githubusercontent.com/30416150/28754894-ccd0e94e-751c-11e7-9c6e-5f2adb9aa2a9.png)
Note to self. Send them a message on any updates.

**Comment by rsbfox** [comment]
Oh I get this too. Didn't really notice till I turned on fps overlay. But I have an old computer so I was just used to bad fps.

**Comment by NoEffex** [comment]
I think it's actually a Java bug on macOS. I believe it's fixed in more recent versions but the bug that used to exist was definitely fixed in the JetBrains distribution of Java (https://bintray.com/jetbrains/intellij-jdk/openjdk8-osx-x64/964.2#files). I was pretty sure we replaced the JRE inside the app with this one but it's possible we didn't.

**Comment by rsbfox** [comment]
Java version: 1.8.0_20-ea

That should be the patched JetBrains Java but just jiggling mouse takes me from 50 to 10 fps in fixed mode software renderer.

**Comment by rsbfox** [comment]
Java version: 1.8.0_152-release

Downloaded that Java you linked. Icon in dock is now Duke starting jar with that. Fps still drops some moving mouse but less so. And OpenGL feels more responsive. Will keep using this thanks.

**Comment by rsbfox** [comment]
Merged into #140 

Anyone with this issue, try using macOS fix script pinned to discord.gg/osbuddy #support channel.
