### ISSUE TITLE
Agility: Mark of grace marker not clipped to minimap

### ISSUE THREAD

**Issue by rsbfox** [rsbmatt/OSBuddy#84]
![image](https://user-images.githubusercontent.com/30416150/28745398-8dbb00f0-7445-11e7-96fd-c9d049899515.png)
v3.0.13

**Comment by rsbmatt** [comment]
Fixed in beta, v3.0.13.4

- [x] Fixed minimap clipping issue
- [x] Fixed bug causing hulls to distort when rotating camera
- [x] Cleaned up a bit of the 2d projection code
