### ISSUE TITLE
Timer Manager: Home teleport timer timer not showing

### ISSUE THREAD

**Issue by rsnjames** [rsbmatt/OSBuddy#87]
Not sure what's causing this, but the timer isn't coming up telling me how long until I can use the home teleport again. 

![image](http://i.imgur.com/ejAfEx2.png)

OSBuddy version: 3.0.13

Edit: Resetting timer manager settings seems to have fixed the issue. Closed the issue.

**Comment by rsbfox** [comment]
Could you please reset timer manager settings? I've tried a bunch of home tele starts and timer started every time. I think this is triggered by the animation. Could some glitch at the right time let you tele without it? Try home tele while being pelted by snowballs.

**Comment by rsnjames** [comment]
I can reset it tomorrow when I'm online. If it helps at all, the timer showed up the first time I home teleported but then went away and wouldn't show up again after. (If it makes any difference I was home teleporting on arceeus spellbook).
