### ISSUE TITLE
Option Reorder: Hide all options on bank booths

### ISSUE THREAD

**Issue by rsbfox** [rsbmatt/OSBuddy#94]
This would be off by default. Runecrafters try to always use banker instead because it's one game tick faster. Clicking on booth is a common misclick. This would be a good QOL and fit well with the option reorder left click bankers.
![image](https://user-images.githubusercontent.com/30416150/28755493-4b89571e-752a-11e7-8a3e-490368b55405.png)
Limiting to just edgeville and being off by default should hopefully stop anyone thinking it's a bug.

**Comment by rsbfox** [comment]
Notify Natn#1422 on any updates to this. It's his suggestion.

**Comment by NoEffex** [comment]
It's a bit tricky due to the fact that those booths share an ID with the other booths, which means either we change one or we change them all. It's technically possible to differentiate but it's computationally intensive. Would hiding the options on all of them as an off-by-default feature work?

**Comment by jannicklorenzen** [comment]
Hiding them all was initially suggested for Edgeville bank fights. I don't see why it would be a problem to disable them all, if people have to enable the setting themselves.

**Comment by rsbfox** [comment]
@NoEffex In hindsight this should be in Option Reorder not Runecrafting. See: #124 
Thanks for the feedback.

I didn't consider non-runecrafting usage thanks Noizexx. Also it should really be an option to hide everything from bank booths. Every option on the booths is on the banker anyway. So this only serves to reduce misclicks when right clicking.

Off by default would be safe.

Edit: Also other booths exist. But I'm told the option reorder code can search for all objects with that name and set everything to null I assume.
![image](https://user-images.githubusercontent.com/30416150/28971597-81abc736-78fa-11e7-8665-9703a72f45f5.png)
