### ISSUE TITLE
Status Indicators: Doesn't hide when bank interface open

### ISSUE THREAD

**Issue by jannicklorenzen** [rsbmatt/OSBuddy#95]
Even when the option to do so is enabled.
![image](https://user-images.githubusercontent.com/30437792/28756257-3fcc217c-756b-11e7-858a-c15cb31d5ad4.png)

OSBuddy v3.0.13

**Comment by rsbfox** [comment]
This isn't an option on prayer indicators. So I think that toggle does not apply. Using #42 to ask for a toggle to hide when bank is open. Else you have the situation where a toggle in current boosts is impacting how the prayer plugin works.
