### ISSUE TITLE
Option Reorder: Left click exchange tool leprechaun

### ISSUE THREAD

**Issue by rsnjames** [rsbmatt/OSBuddy#97]
List of farming patches in OSRS: http://oldschoolrunescape.wikia.com/wiki/Farming/Patch_locations

**Comment by rsbfox** [comment]
![image](https://user-images.githubusercontent.com/30416150/28779982-2092cd34-75d3-11e7-8555-131a261703ed.png)
Pretty sure for option reorder they just need npc name and options to switch. So here you go. :)

**Comment by rsbmatt** [comment]
Added in beta, 3.0.15.1
